### ISSUE TITLE
Schema validation on deployment descriptors with verifier disabled

### ISSUE THREAD

**Issue by ggam** [payara/Payara#1014]
I'm deploying and app with the following web.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns="http://xmlns.jcp.org/xml/ns/javaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd"
         version="3.1">
    <security-constraint>
        <web-resource-collection>
            <url-pattern>/*</url-pattern>
        </web-resource-collection>
    </security-constraint>
</web-app>
```

The verifier is disabled for this deployment, but it still complains with the following error: 

> Error occurred during deployment: Exception while deploying the app [test] : org.xml.sax.SAXParseException; lineNumber: 8; columnNumber: 26; Deployment descriptor file WEB-INF/web.xml in archive [test]. cvc-complex-type.2.4.a: Se ha encontrado contenido no válido a partir del elemento 'url-pattern'. Se esperaba uno de '{"http://xmlns.jcp.org/xml/ns/javaee":web-resource-name}'.. Please see server.log for more details. 

This also happens when an empty beans.xml is given, although the CDI spec explicitly allows it.

**Comment by lprimak** [comment]
@ggam According to this Oracle documentation: https://docs.oracle.com/cd/E19879-01/820-4337/beadq/index.html, the validator tool is meant to introspect not just the XML file syntax against DTD, but it's actual content for compatibility (deeper inspection).
According to my understanding, regular deployment will check XML validity against DTD, which is the expected behavior, even if the verifier tool is disabled.

You are correct about the beans.xml issue, that's a bug

**Comment by lprimak** [comment]
Payara internal bug https://jira.payara.fish/browse/PAYARA-1005

**Comment by lprimak** [comment]
@ggam I tested current Payara with empty beans.xml, and it does indeed work as designed.  Empty beans.xml needs to be truly empty, not even a whitespace.

**Comment by lprimak** [comment]
@ggam, is this still an issue for you?  If yes, please elaborate, if not, please close the ticket
thanks!

**Comment by lprimak** [comment]
Both Empty beans.xml and the validation issues work as designed
