### ISSUE TITLE
Problem with compressed http requests

### ISSUE THREAD

**Issue by Hoobie** [payara/Payara#1038]
Exception:
```xml
<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/">
<S:Body>
<S:Fault xmlns:ns4="http://www.w3.org/2003/05/soap-envelope">
<faultcode>S:Client</faultcode>
<faultstring>Couldn't create SOAP message due to exception: XML reader error: com.ctc.wstx.exc.WstxUnexpectedCharException: Illegal character ((CTRL-CHAR, code 31))
at [row,col {unknown-source}]: [1,1]</faultstring>
</S:Fault>
</S:Body>
</S:Envelope>
```

Still occurs in Payara `4.1.1.162`.

Related Glassfish issue: [GLASSFISH-20726](https://java.net/jira/browse/GLASSFISH-20726)
Related Grizzly issue: [GRIZZLY-1669](https://java.net/jira/browse/GRIZZLY-1669)

**Comment by lprimak** [comment]
@Hoobie one good thing would be to vote on GRIZZLY-1669
I have voted

**Comment by mikecroft** [comment]
The Grizzly patch has been incorporated, so this should hopefully be included in the next release (provided it all builds OK)

**Comment by mikecroft** [comment]
Internal issue ID to upgrade Grizzly: `PAYARA-1026`

**Comment by Hoobie** [comment]
@mikecroft, the error still occurs in Payara Server 4.1.1.171 #badassfish (build 137) :(

**Comment by mikecroft** [comment]
Hi @Hoobie we had to downgrade Grizzly, unfortunately, because there was an issue that came up in 2.3.28 that wasn't there in 2.3.27. It was decided that the problems of .27 was less traumatic than introducing new and different problems for one release.

The .29 version of Grizzly has just recently been released, though, so we can probably get it changed and merged in soon. Once that's done then the nightly build will be available to you, though it will be a while before another formal release is out.

Here's the link to the downgrade, which references 2 issues that were the reason for it:
https://github.com/payara/Payara/pull/1373

**Comment by Hoobie** [comment]
Hello, @mikecroft 
Thank you for the quick reply. Somehow I missed this information. I hope that these issues are fixed in the current Grizzly's version.
