### ISSUE TITLE
Way to re-read config files without undeploy

### ISSUE THREAD

**Issue by edilmar** [payara/Payara#1059]
Hi,
I would like to know if it is possible to re-read config files (web.xml, ejb-jar.xml, persistence.xml, etc) without undeploy/deploy the app. I have a webapp used by many enterprises, where I just config a new database for each new enterprise, without to be necessary to change the Java code. The problem is that, for each new enterprise, I have to undeploy/deploy the app because config files are changed, mainly ejb-jar.xml and persistence.xml.

**Comment by edilmar** [comment]
I would like something like CLI commands, not third-party tools like JRebel.

**Comment by Davio** [comment]
You can try asadmin disable app and asadmin enable app. It's faster than redeploying and might pick up the changed config.

**Comment by edilmar** [comment]
@Davio the "enable process" consumes the same time of "deploy process", re-reading the configs, re-charging the persistence units, re-processing the CDI files, etc.

**Comment by mikecroft** [comment]
I discussed this with some developers and we're going to close this as "wontfix" at this stage. The reason being that there is no clear definition of how it would work in any way that is different from the current asadmin `disable`/`enable` subcommands.

Personally, I'm not sure how possible it would be to add the feature in a way that would give any noticeable improvement over `disable`/`enable` because of all the potential edge-cases that would have to be considered and necessitate most of the app being reloaded anyway.

If you can think of a more narrow and specific enhancement request, though, then we can always have another look because that might be more achievable.
