### ISSUE TITLE
Payara does not cache exceptions

### ISSUE THREAD

**Issue by jerrinot** [payara/Payara#1138]
The `cacheException` flag is always [set to `false`](https://github.com/jerrinot/Payara/blob/418333155b32502490c3865912688191203e1a5e/appserver/payara-appserver-modules/payara-jsr107/src/main/java/fish/payara/cdi/jsr107/CacheResultInterceptor.java#L77-L77).

Is this intentional or is it just a left-over?

**Comment by OndrejM** [comment]
It must be a left-over, because the variable `cacheException` declared on line [77](https://github.com/jerrinot/Payara/blob/master/appserver/payara-appserver-modules/payara-jsr107/src/main/java/fish/payara/cdi/jsr107/CacheResultInterceptor.java#L77) is never used. Whole line could be removed without any effect.

**Comment by jerrinot** [comment]
oh, `cacheException` vs `cacheExceptions`. that's a good one, I completely missed that!

**Comment by OndrejM** [comment]
@jerrinot, did you report this issue because you assumed the behavior from sources, or did you really observe that exceptions are not caught?

**Comment by jerrinot** [comment]
the report was based purely on my (broken) reasoning. You can close it + ideally remove that extra line. ahem, static code analysis, ahem:)
