### ISSUE TITLE
JAX-RS sub-resource without HTTP method annotation is invokable

### ISSUE THREAD

**Issue by peraxel** [payara/Payara#1147]
Having a JAX-RS sub-resource without HTTP method annotation will expose it as invokable using any HTTP method. Making a request to such sub-resource gives HTTP response code 404, but the method is invoked anyway. Expected behaviour is HTTP response code 405 and needless to say, the method should not be invoked.

Reproducible using the attached file:

Unpack [jaxrs-bug.tar.gz](https://github.com/payara/Payara/files/552439/jaxrs-bug.tar.gz)
Copy payara-4.1.1.163.zip into jaxrs-bug dir
./run.sh

**Comment by peraxel** [comment]
I had a closer look at the [Jersey docs](https://jersey.java.net/documentation/latest/jaxrs-resources.html). Looks like this could actually be intended behaviour for sub-resource locators. I still think the kind of "misuse" I show in my example app should be prevented. Could be prevented by making sure that the return type of a sub-resource locator method has at least one HttpMethod or Path annotation (in case of nested sub-resource locators).

**Comment by mulderbaba** [comment]
@thanks for the reproducer @peraxel.

**Comment by mulderbaba** [comment]
@peraxel I went through the JAX-RS documents and it's stating that sub-resource locator methods should not be annotated with the HTTP methods so your impl. is right on that part. But the locator method that you implemented is not returning a sub-resource back but modifying logic on the `GenericResource` itself. I think that should be done in the SubResource in order to prevent 404. A sample implementation that handles your case for the GenericResource and SubResource would be as follows:
```
@Path("a")
@Singleton
public class GenericResource {

    private String state = "original value";

    SubResource subResource = new SubResource(this);

    public void setState(String state) {
        this.state = state;
    }

    @GET
    public String get() {
        return state;
    }

    @Path("b")
    public SubResource getSubResource() {
        return subResource;
    }
}
```

```
public class SubResource {

    private final GenericResource genericResource;

    public SubResource(GenericResource genericResource) {
        this.genericResource = genericResource;
    }

    @GET
    public String get() {
        genericResource.setState("ALTERED!!!");
        return "b";
    }
}
```
So with the snippets, execution of 3 requests given below will be invoked with no problem (404).
request for '<context>/api/a' --> original value
request for '<context>/api/a/b' --> b
request for '<context>/api/a' --> ALTERED!!!

Let me know if all these sound right for you.

**Comment by peraxel** [comment]
Yes, you are right. As I wrote in my previous comment, I think this is the intended behaviour. But I still think the kind of "misuse" I demonstrated in my example should be prevented. Will try to file that to the Jersey team instead. Closing this.
