### ISSUE TITLE
Microservices with Payara Micro - proper deployment c:Question

### ISSUE THREAD

**Issue by vasouv** [payara/Payara#1170]
Greetings! I'm trying to understand Payara Micro and microservices a bit, without jumping to Docker yet. All of my testing is done on my laptop.

I deploy my two microservices like you would with Payara Micro in a Docker container:
`java -jar backend.jar --deploy apollo.war --port 8383`
`java -jar backend.jar --deploy artemis.war --port 8484`

Now let's say I want to start another Apollo and Artemis instance to scale them for higher load:
`java -jar backend.jar --deploy apollo.war --port 8384`
`java -jar backend.jar --deploy artemis.war --port 8485`

That's it, isn't it? I see the instances clustering together in a single cluster and I guess it's ready? I know the ports work because they return data, but maybe I shouldn't assign the ports myself to the second instances? Should I have two separate clusters for Apollo and Artemis?

**Comment by OndrejM** [comment]
@vasouv, it depends on what you are trying to achieve. If you expect automatically load balance your requests, this is not supported. You still need to put a load balancer, like HaProxy, to route the requests to multiple payara micro instances, so that you may access your service by a unified URL. The cluster helps you with distribution of session or cached data accross all instances.

Please, describe what you would like to achieve to help you better. You didn't any mistake with running the same application in the same cluster on different ports. All applications listen on a different port. But from your description I don't know what actually does not work.

**Comment by vasouv** [comment]
@OndrejM actually you've covered me :) I wasn't trying to achieve anything specific, just understand how microservices and scaling work in a simple way.

You verified that I launch the other instances correctly on the same cluster, that's already enough for me. And since you said I need a load balancer to route to the other instances, you've given me my answer :)

**Comment by OndrejM** [comment]
That was simpler than I expected then :) 

If you want to turn on session replication, just make sure your applications have `<distributable/>` element in their `web.xml`. Otherwise you would want to configure sticky sessions, so that the load balancer will route the same user always to the same instance.
