### ISSUE TITLE
Asadmin recorder problem on create-file-user

### ISSUE THREAD

**Issue by ezequielgaggioli** [payara/Payara#1239]
**The create-file-user command that generates asadmin recorder fail when is executed by terminal:**

```
Password not allowed on command line: userpassword
Usage: asadmin [asadmin-utility-options] create-file-user
	[--authrealmname <authrealm_name>] [--target target] 
	[--groups user_groups[:user_groups]*] 
	[-?|--help[=<help(default:false)>]] username
Command create-file-user failed.

```
## Steps to reproduce (Only for bug reports) 

1 -**  Start the domain

    ./asadmin start-domain domain1

2 -**  Create auth realm

`create-auth-realm --classname=com.sun.enterprise.security.auth.realm.file.FileRealm --property=file=$\{com.sun.aas.instanceRoot\}\/config\/web-keyfile:jaas-context=fileRealm: --target=default-config web_security`

3 -**  Create file user (**As generated by the asadmin recorder**)

`create-file-user --groups=test-goup --userpassword=test1234 --target=default-config --authrealmname=web_security test-user`

## Environment ##

- **Payara Version**: 4.1.1.164 #badassfish (build 28)
- **Edition**: Full
- **JDK Version**: 1.8.0_101
- **Operating System**: Linux

**Comment by mikecroft** [comment]
hi @ezequielgaggioli what were the steps you used in the Admin Console to generate these commands?

**Comment by Pandrex247** [comment]
@mikecroft Managed to recreate this. From the Admin Console:

* Turn on asadmin recorder
* server-config > Security > Realms > admin-realm > Manage Users > New
* Fill out some details and press OK
* Check the command printed to the _asadmin-commands.txt_ file, and run it against the command line with a slight alteration:
    `Password not allowed on command line: userpassword`

This happens because, as the error states, you cannot enter the `userpassword` option from the command line: you have to enter it when prompted. I imagine there's likely a couple of other authentication commands laying around that have similar restrictions.

So while what's being recorded isn't _wrong_ per sé, it's not usable, which kind of defeats the purpose.

**Comment by mikecroft** [comment]
The `--paswordfile` option should point to a text file with the property `AS_ADMIN_USERPASSWORD` present. I'm not sure whether creating that file could or should fall under the responsibility of the recorder, though.

**Comment by mikecroft** [comment]
Internal issue ID for handling password file: `PAYARA-1555`. More details in PR #1722

**Comment by mikecroft** [comment]
Previous PR superceded by #1752, now merged
