### ISSUE TITLE
How to create-jdbc-connection-pool for DB2

### ISSUE THREAD

**Issue by hugree** [payara/Payara#1252]
I have a simple problem, I think.

I'm trying to setup a datasource that connects to DB2

When I have my datasource configured in web.xml
```
<data-source>
	<name>jdbc/myDS</name>
	<class-name>com.ibm.db2.jcc.DB2Driver</class-name>
	<url>jdbc:db2://db2.emb24.consdata.local:60000/IB24:retrieveMessagesFromServerOnGetMessage=true;</url>
	<user>USER</user>
	<password>PASSWORD</password>
</data-source>
```

everything is fine. I have put my drivers into glassfish/lib.

Now I tried to automate this inside a Docker container so I turned to asadmin command  

```
./asadmin create-jdbc-connection-pool --datasourceclassname com.ibm.db2.jcc.DB2Driver --restype javax.sql.DataSource --property user=USER:password=PASSWORD:URL='jdbc:db2://db2.emb24.consdata.local:60000/IB24:retrieveMessagesFromServerOnGetMessage=true;' myDS
```

When I run this I get the following error
```
remote failure: Invalid property syntax, missing property value: db2
Invalid property syntax, missing property value: db2
```

I tried double quotes for the URL parameter and I get the same result.

What am I missing here?

**Comment by OndrejM** [comment]
You need to escape all the colons that are not property separators. Enclosing the value in quotes doesn't help - the quotes will be eaten by the shell. 

Your command should read like this:

```
./asadmin create-jdbc-connection-pool --datasourceclassname com.ibm.db2.jcc.DB2Driver --restype javax.sql.DataSource --property 'user=USER:password=PASSWORD:URL=jdbc\:db2\://db2.emb24.consdata.local\:60000/IB24\:retrieveMessagesFromServerOnGetMessage=true;' jdbc/emb24ds-business2
```

Above, all the colons in the URL property are prepended by '\' to escape them. The whole `--property` argument is enclosed in quotes, because '\' would be escaped by the shell and all backward slashes would need to be double otherwise.

Have a look at this for more details: https://docs.oracle.com/cd/E19798-01/821-1758/asadmin-1m/index.html#Escape%20Characters%20in%20Options%20for%20the%20asadmin%20Utility

**Comment by mikecroft** [comment]
Hi @hugree - has @OndrejM's suggestion solved your problem?

**Comment by mikecroft** [comment]
Closing this since a solution has been provided. If there is still a problem after properly escaping colons in the string, then we can reopen this.
