### ISSUE TITLE
Payara Embedded Crash

### ISSUE THREAD

**Issue by realityforge** [payara/Payara#129]
Hi,

We have just been attempting to use the embedded-all artifact from the jenkins snapshot on the 22/12/2014 and keep running into the same problem, regardless of what app we try to deploy to it. The exception is at https://gist.github.com/realityforge/60cc0222013fddf44c63

**Comment by Pandrex247** [comment]
The embedded jar should now have the correct jbatch jar packaged with it, and so you should no longer get that exception. 

There was a mistake with our Jenkins build not specifically cleaning out the extra embedded directories, as they are otherwise skipped with a "mvn clean" run from the root directory.

Thanks
