### ISSUE TITLE
Is there some way to reload config files after the webapp is deployed/is running?

### ISSUE THREAD

**Issue by edilmar** [payara/Payara#1388]
My env is Payara last version + Netbeans + JSF/Rich/Prime + JPA/Hibernate.
I use these config files: 
- WEB-INF/ejb-jar.xml
- WEB-INF/web.xml
- classes/META-INF/persistence.xml
For example, sometimes I need to include a new persistence-unit in persistence.xml + ejb-jar.xml,
where I use JNDI to get the PU into Java code.
But, when I change the config files, I always have to undeploy/deploy the complete webapp.
If possible, I would like some way to call a Payara internal method from API to reload the
config files. Then, I could use the PU in my JNDI code transparently.

**Comment by mulderbaba** [comment]
One option here would be trying [JRebel](https://zeroturnaround.com/software/jrebel/) and its integration w/ [EclipseLink](http://manuals.zeroturnaround.com/jrebel/misc/integrations.html#frameworks) to see if it suffices your needs.

**Comment by edilmar** [comment]
Hi, I need this in production environment and I use HIbernate, not able to use EclipseLink.

**Comment by lprimak** [comment]
@edilmar You have been asking same / similar question for quite a while, for example #886 
I suggest you look deeper at what your requirements actually are.  The "deployment process" is the process of reading the config files and loading classes under the covers.  What you are asking is about 90% of the deployment process and doesn't make sense in my view.

I think what you should be looking at is some kind of a load balanced / rolling upgrade setup which you have more than one instance running and you can switch over to the new instance / version of your application when you are ready, and not hinging everything on redeployment of your application on a single running instance of Payara and your application.

Take a look at the rolling upgrades blog, it's been simplified a lot for .171 release and may help you achieve what you are actually looking for: http://blog.payara.fish/payara-server-rolling-upgrades

**Comment by mulderbaba** [comment]
@edilmar JRebel integrates with Hibernate and Hibernate Validator as well. You need hot-reload in production environment? I doubt you'd really really want that. as @lprimak mentioned rolling upgrades should do the trick for you.

**Comment by mikecroft** [comment]
Hi @edilmar - hot reloading has been addressed by #886 as @lprimak mentioned. This isn't a feature we're looking to add, since it's already satisfied by JRebel, but this is not a product to be used in production. ZeroTurnaround put significant effort into creating an equivalent that would work in production called LiveRebel, but [discontinued it shortly after launch.](https://zeroturnaround.com/rebellabs/goodbye-liverebel).

Rolling upgrades will give you the zero downtime that you need or, if you wanted to move to a more modern container-driven deployment style, there are third party tools which will allow you to achieve the same thing with docker.

I'll close this now, since it's not something we are going to pursue.
