### ISSUE TITLE
Refactoring EJB Timer Service Table name.

### ISSUE THREAD

**Issue by Taymindis** [payara/Payara#1418]
To refactoring the EJB Timer Table name via asadmin console. 

Expected:- 
To able to refactor the ejb timer table name and ejb timer job status table name via ejb timer service page.

Current Issue:-
The Ejb Timer Table and EJB Timer job status are fixed schema

**Comment by Taymindis** [comment]
why this link has no effect
<img width="433" alt="alternativestoreejbtimer" src="https://cloud.githubusercontent.com/assets/14217761/23584661/98fadd20-01a2-11e7-9c8c-7cf61d1802f6.png">

**Comment by smillidge** [comment]
Note I haven't tried this!!

The timer table name is autogenerated via JPA. The entity is here https://github.com/payara/Payara/blob/master/appserver/ejb/ejb-full-container/src/main/java/org/glassfish/ejb/persistent/timer/TimerState.java#L173 

It MAY be possible to change the table name by updating the __ejb_timer_mappings.xml file stored in this internal war file. glassfish/lib/install/applications/ejb-timer-service-app.war

**Comment by Taymindis** [comment]
@smillidge I am sorry, How can I change this at runtime? did you mean re-compile the war?

**Comment by mikecroft** [comment]
Hi @Taymindis I don't think this is particularly feasible in the way you're asking. The EJB timer service is a compiled WAR, so that would need to be modified if you wanted to change something like the table name, as @smillidge says. I don't think this is something we can easily add as a feature to the admin console.

It may be possible to change the way it works, but that would be significant effort so I don't think it's something we could do unless it was a sponsored feature, for example. What are your thoughts @smillidge?

**Comment by mikecroft** [comment]
(as for the broken link in the docs, that was documentation for a feature which has not yet been released. The broken link has now been removed.)

**Comment by OndroMih** [comment]
Unfortunately, we’re not able to fit this feature request into our current roadmap. I’m closing this issue. I hope you understand.
