### ISSUE TITLE
loopBack Undefined Symbol

### ISSUE THREAD

**Issue by Taymindis** [payara/Payara#1452]
I am trying to add loopBack on event sender but it does not work

@Inject
@Outbound(loopBack = true)
Event event;

<img width="698" alt="screen shot 2017-03-12 at 9 16 52 pm" src="https://cloud.githubusercontent.com/assets/14217761/23832095/4764b734-0769-11e7-9036-f26e6a0d3769.png">

Why 171 has less file than 162?? No more outbound inbound CDI

**Comment by mulderbaba** [comment]
@Taymindis it's because we refactored the content of payara-micro and introduced the nested jar approach. the artefacts now reside under MICRO-INF/runtime. And you can see the Inbound and Outbound classes in 171 release commit available at: [here](https://github.com/payara/Payara/tree/e28213a281ae7231286e6f0528e642a9d20aafd8/appserver/payara-appserver-modules/payara-micro-cdi/src/main/java/fish/payara/micro/cdi). So the classes are there. But we will soon refactor them and we're going to introduce payara-api artefact.
For the loopback attribute are you getting any exceptions? or it's not working as you expected?

**Comment by Taymindis** [comment]
@mulderbaba I couldn't compile at the by using payara-micro 171. However, I managed to get it done with payara-api installed. 
Thanks.
