### ISSUE TITLE
Verify realm name specified in web.xml /CUSTCOM-61

### ISSUE THREAD

**Issue by ptrwis** [payara/Payara#1465]
# Description #
----------

Server doesn't notify the user in any way about wrong realm name specified in web.xml ( \<login-config\>/\<realm-name\> ). In my case it was just a typo. Verify if realm name exist in AS.

## Expected Outcome

Interrupt deployment, or at least log an error when user tries to authenticate using non existing realm. 

## Current Outcome

Nothing

## Environment ##

- **Payara Version**: 4.1.1.171 #badassfish (build 137)
- **Edition**: Full
- **JDK Version**: 8 uXX - Oracle
- **Operating System**:  Windows

**Comment by mikecroft** [comment]
Created internal issue `PAYARA-1534` for the enhancement.

**Comment by rdebusscher** [comment]
Tracked now as internal issue `CUSTCOM-61`

**Comment by AlanRoth** [comment]
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.
