### ISSUE TITLE
Session replication only working between 2 of 3 instances

### ISSUE THREAD

**Issue by realulim** [payara/Payara#1474]
# Description #
When I start up three instances of Payara Micro with the clusterjsp.war and then enter some session data, it is only replicated between instances #2 and #3. Instance #1 seems to have its own data. 

## Expected Outcome
I would expect that any session data entered on the clusterjsp page of instance #1 is replicated to instances #2 and #3. I would also expect that any session data entered in instances #2 and #3 were replicated to instance #1.

## Current Outcome
See above, only instances #2 and #3 are replicating between themselves.

## Steps to reproduce (Only for bug reports) 

1 -**  Start the first instance
java -jar payara-micro-4.1.1.171.0.1.jar --deploy ./clusterjsp.war

2 -**  Start the second instance
java -jar payara-micro-4.1.1.171.0.1.jar --deploy ./clusterjsp.war --autoBindHttp

3 -**  Start the third instance
java -jar payara-micro-4.1.1.171.0.1.jar --deploy ./clusterjsp.war --autoBindHttp

4 -** Check that each instance is running by opening a browser tab to http://localhost:808[0|1|2]/clusterjsp

5 -** Enter some session data on the various instances and observe replication of said data by hitting "reload" in the three browser tabs

## Environment ##

- **Payara Version**: 4.1.1.171.0.1
- **Edition**: Micro
- **JDK Version**: 1.8.0_65
- **Operating System**: Mac

**Comment by mikecroft** [comment]
Does your test have a load balancer in front to manage your session cookie? If you are hitting the endpoints directly, I would expect you wouldn't see replication happening at all, because you should get a new session each time.

If you wanted to test that the Hazelcast cluster is functioning properly without setting up Apache or Nginx or something, you could use [a simple JCache app, like we have in our Payara-Examples repository](https://github.com/payara/Payara-Examples/tree/master/rest-examples/rest-jcache). If that is deployed to your Payara Micros, then you should be able to `curl` with an HTTP `GET` to verify the default "hello world" output from [1], then use `PUT` to add some new data to instance [2] and get the same new data out from [1] or [3].

**Comment by realulim** [comment]
No load balancer, but I was hitting the endpoints with the same browser (different tabs), so I thought cookie should not be a problem. And in fact it did replicate between instances #2 and #3. And when I retried the procedure just now per the description above, I found that suddenly everything works as expected. The session data is replicated between all 3 instances.

So apparently I previously managed to start the three instances in a way that something broke. Sorry for that bogus report, but I did verify twice before reporting. I could even see that all three nodes joined the cluster in the stdout output. Or maybe it has something to do with the cookie after all and my browser was in a funny state.

**Comment by mikecroft** [comment]
Interesting! If you're ever in doubt, both the Chrome and Firefox developer tools will let you view the cookies you have for a given web page, though you need to enable "Storage" in the Firefox developer tools settings first. Thanks for confirming it works!
