### ISSUE TITLE
Where is the document of PayaraMicro.setUserLogFile method?

### ISSUE THREAD

**Issue by ahuglajbclajep** [payara/Payara#1526]
# Description #
[This page](https://payara.gitbooks.io/payara-server/content/documentation/payara-micro/logging-to-file.html) has a description of `PayaraMicro.setUserLogFile(String str)` but why can not I find it in the [document](http://payara.github.io/Payara/nucleus_API/payara-modules/payara-micro/target/apidocs/fish/payara/micro/PayaraMicro.html)?

**Comment by mikecroft** [comment]
Sorry for being so late in getting back to you on this. The issue is that those javadocs are out of date.

We have slightly more up-to-date javadocs in [the organisation GitHub pages site which does include that method](https://payara.github.io/appserver_API/payara-micro/apidocs/). We're working on updating all the Javadocs for Payara Micro, Payara Server and our API JAR, which we will link from https://payara.github.io/
