### ISSUE TITLE
Can't create Connector Connection Pool for inbound RA deployed on a cluster

### ISSUE THREAD

**Issue by DylanVRRandall** [payara/Payara#1553]
# Description #
----------

If an Inbound Resource Adapter (RA) is deployed on a cluster then the subsequent creation of a Connector Connection Pool for that RA will fail due to a ClassNotFoundException for the com.sun.genericra.inbound.ActivationSpec class.

If the RA is instead deployed on server (instead of a cluster) then the creation of the Connector Connection Pool succeeds.

## Expected Outcome

The RA should be able to be created in a clustered environment.

## Current Outcome

The Connector Connection Pool for the deployed RA can not be created.

## Steps to reproduce (Only for bug reports) 

**1) Download Oracle's "Generic Resource Adapter for JMS" from here:**

[http://genericjmsra.java.net/docs/Releases.html](http://genericjmsra.java.net/docs/Releases.html)

**2) Create a cluster with single instance c1_1, and start the cluster:**

_asadmin create-cluster cluster1
asadmin create-instance --node localhost-domain1 --cluster cluster1 c1_1
asadmin start-cluster cluster1_

**3) Deploy the RA on the cluster:**

_asadmin deploy --target cluster1 genericra.rar_

**4) Attempt to create Connector Connection Pool for the RA:**

_asadmin create-connector-connection-pool --raname genericra --connectiondefinition javax.jms.QueueConnectionFactory genericra_pool_

remote failure: Connector connection pool genericra_pool creation failed. Unable to load class [ com.sun.genericra.inbound.ActivationSpec ]
Unable to load class [ com.sun.genericra.inbound.ActivationSpec ]
Command create-connector-connection-pool failed.

## Context (Optional)

I am trying to communicate to IBM MQ through a clustered environment.

## Environment ##

- **Payara Version**: 4.1.1.171 #badassfish (build 137)
- **Edition**: Full
- **JDK Version**: jdk1.7.0_79 Oracle
- **Operating System**: Mac

**Comment by michaelranaldo** [comment]
Thanks for the nicely written report!

Created internal issue PAYARA-1622

**Comment by michaelranaldo** [comment]
Hi @DylanVRRandall ,

Looking at this again, if you deploy the genericra.rar to the DAS with:

`asadmin deploy genericra.rar` 

you should be able to resume configuring the resource adapter.

**Comment by DylanVRRandall** [comment]
Hi @michaelranaldo 

Thank you for your reply. 

Yes agreed, I am able to use  and configure the RA in the DAS, I have done this to continue with development of the application however we still cannot go do production without the clustering.

**Comment by smillidge** [comment]
Hi @DylanVRRandall I don't believe this is a bug. The problem is that on deployment of a RAR file in JavaEE7 there are some additional validation requirements that the DAS needs to now make including that the specified ActivationSpec class is derived from ActivationSpec which means the DAS needs to load the classes in RAR file.

As a result of that you need to target the RAR when deploying to both the DAS AND the Cluster. The rar will be usable fine from the cluster.

**Comment by mikecroft** [comment]
Hi @DylanVRRandall I think @michaelranaldo is saying that you *can* still use the genericra in a clustered environment, but you need to deploy the RAR to *both* the cluster *and* the DAS.

The reason is that the DAS needs to find the implementation class from the resource adapter to be able to create the connection pool, even if the resources are going to be on the cluster.

**Comment by DylanVRRandall** [comment]
Hi Guys

Thank you both for your replies. I will try this and get back to you.

**Comment by DylanVRRandall** [comment]
Hi Guys

Through our investigation I believe that this isn't a bug. Locally, I am able to deploy the application to the cluster and leverage the RA in the cluster. 

Thank you for your time and effort.

**Comment by michaelranaldo** [comment]
Hi @DylanVRRandall,

Happy to have helped!
