### ISSUE TITLE
Deployment exception

### ISSUE THREAD

**Issue by akyekth** [payara/Payara#1567]
Hi trying to deploy project in glassfish 4.1.1 i got the below exception

```
Payara 4.1|javax.enterprise.system.core|_ThreadID=94;_ThreadName=admin-thread-pool(6);_TimeMillis=1493383149301;_LevelValue=1000;|Exception while deploying the app [hopsworks-api] : The lifecycle method [stop] must not throw a checked exception. Related annotation information: annotation [@javax.annotation.PreDestroy()] on annotated element [public void io.airlift.http.server.HttpServer.stop() throws java.lang.Exception] of type [METHOD]
The lifecycle method [stop] must not throw a checked exception. Related annotation information: annotation [@javax.annotation.PreDestroy()] on annotated element [public void io.airlift.http.server.HttpServer.stop() throws java.lang.Exception] of type [METHOD]
at org.glassfish.apf.impl.AnnotationProcessorImpl.process(AnnotationProcessorImpl.java:375)
at org.glassfish.apf.impl.AnnotationProcessorImpl.process(AnnotationProcessorImpl.java:383)
at org.glassfish.apf.impl.AnnotationProcessorImpl.processAnnotations(AnnotationProcessor
```

If anyone got this exception, please help me.

Thanks in Advance
Aruna

**Comment by mikecroft** [comment]
Exception while deploying the app [hopsworks-api] : The lifecycle method [stop] must not throw a checked exception. Related annotation information: annotation [@javax.annotation.PreDestroy()] on annotated element [public void io.airlift.http.server.HttpServer.stop() throws java.lang.Exception] of type [METHOD]
The lifecycle method [stop] must not throw a checked exception. Related annotation information: annotation [@javax.annotation.PreDestroy()] on annotated element [public void io.airlift.http.server.HttpServer.stop() throws java.lang.Exception] of type [METHOD]

The error message is pretty self-explanatory. The method `io.airlift.http.server.HttpServer.stop()` is annotated with `@PreDestroy` and also throws a checked exception, which is not valid in Payara Server. 

I'm not really sure what you're trying to do here, since Airlift is a REST framework and JAX-RS is already provided in Payara Server with Jersey. The class where the error is coming from also looks like it's trying to boot a Jetty server too, and that's really not what you want to happen.

If you want to use this framework, I think you will need to use it apart from Payara Server - there isn't anything we can fix here.

**Comment by OndrejM** [comment]
@akyekth, maybe turning off implicit CDi scanning would help - try following my answer to this question: http://stackoverflow.com/a/43717446/784594
