### ISSUE TITLE
ENH: NAT-configuration for standalone IIOP client 

### ISSUE THREAD

**Issue by Findulas** [payara/Payara#1670]
# Description #
----------

We need to connect to a payara server behind a clientside firewall with static nat. The server configuration cannot/should not be changed. So there should be a configuration for a standalone client to nat the via GIOP transfered address.

## Expected Outcome

The network is set up with a firewall doing a static nat:

standalone client <-vpn-> firewall (nat) <-lan-> payara

Most of the clients connect to the payara server from inside the lan. So the server configuration should not be changed for the vpn clients.

A solution would be to configure an NAT for the transmitted addresses inside the iiop client of the standalone application. This translation needs to match those on the firewall. This way clients behind a natting firewall can connect to the server without any changes made to the server configuration

## Current Outcome

This solution would only match static nats.

## Environment ##

- **Payara Version**: 4.1.1.171
- **Edition**: Full
- **JDK Version**: 8 u131 - OpenJDK
- **Operating System**: Windows
- **Database**: PostGres

**Comment by fturizo** [comment]
Greetings @Findulas,  Indeed as you mention remote EJB communication on Payara Server struggles at locating remote EJBs due to the way the GIOP communication packets handle the server's address when going through a NAT or a VPN. I've opened the JIRA Issue `PAYARA-1811` so the developers can give me input if this scenario is workable and the effort to do it is manageable. I'll come back to you once I have more information.

**Comment by mikecroft** [comment]
Hi @Findulas - we are looking at a solution for #1406 and think it would solve your problem here, since we could tunnel remote EJB calls over HTTP or Websockets. Would that be an acceptable resolution for your use case too?

**Comment by Findulas** [comment]
That seems to be a solution to me. Can you point me to an documentation?

Bernd (aka Findulas)

Mike Croft <notifications@github.com> schrieb am Do., 13. Juli 2017, 17:17:

**Comment by fturizo** [comment]
@Findulas, there's no documentation for what we are proposing since this change would only be made internally to support HTTP/Websockets as the transport protocol for remote calls. HTTP and WebSockets would allow handling the routing of remote calls through firewalls and on NAT environments far simpler since such use cases have been managed and solved already, which is why @mikecroft  was asking if this would be an acceptable solution.

**Comment by rdebusscher** [comment]
Hi @Findulas 

You can find more information around remote EJB over HTTP in this [blog : RemoteEJB via HTTP](https://blog.payara.fish/remote-ejb-via-http).

Regards
Rudy
