### ISSUE TITLE
Web session clustering does not work

### ISSUE THREAD

**Issue by robelcik** [payara/Payara#1689]
# Description #
----------
Web session clustering (via Hazelcast) does not work (on Payara Micro 4.1.2.172) when there are third-party libraries in `WEB-INF/lib` directory.

It might be related to #1676 

## Expected Outcome
I expect web sessions to be clustered as they were in `4.1.1.171.1`.

## Current Outcome
Sessions are not distributed among the nodes. I'm getting the following error:
```
Invalid Session Management Configuration for non-distributable app [clusterjsp] - defaulting to memory: persistence-type = [hazelcast] / persistenceFrequency = [web-method] / persistenceScope = [modified-session]
```

## Steps to reproduce (Only for bug reports) 

1. Download [clusterjsp.war](http://blogs.nologin.es/rickyepoderi/uploads/SimplebutFullGlassfishHAUsingDebian/clusterjsp.war) from http://blog.payara.fish/payara-micro-clustering
2. Add a third-party lib to the war's `WEB-INF/lib`, e.g. [slf4j-api-1.7.25.jar](http://central.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar)
3. Run several Payara Micro instances by using a command like `java -jar payara-micro.jar --port 808x --deploy clusterjsp.war`
4. Play with the application as described in the linked blog post

## Environment ##

- **Payara Version**: 4.1.2.172
- **Edition**: Micro
- **JDK Version**: 8 u66 Oracle
- **Operating System**:  Windows 10

**Comment by smillidge** [comment]
This does look like a bug has appeared. We'll do some more work to see if we can reproduce.

**Comment by lprimak** [comment]
Internal Payara issue PAYARA-1765

**Comment by mirozitnansky** [comment]
this issue is still present in current Payara Server  5.2021.4
once we add external lib in to WAR _WEB-INF\lib\primefaces-10.0.0.jar_ , server generates new JSESSIONID for each request over balancer
once lib is removed, server holds JSESSIONID between requests and starts to generate new cookie  JSESSIONIDVERSION

attaching examples, deploy with availability [CrudView.zip](https://github.com/payara/Payara/files/6748401/CrudView.zip)
_CrudView3.war_ doesn't include primefaces-10.0.0.jar - availability works
_CrudView4.war_ does include primefaces-10.0.0.jar - availability is not working 

I tested it on "real" environment, but can be also easily tested on localhost-domain1 > 2 instances (1 deployment group) deployed without balancer
and switching ports - on CrudView3 JSESSIONID is kept between calls
`C:\curl\curl.exe http://localhost:28080/CrudView/index2.xhtml -I -c cookie -b cookie -v`
`C:\curl\curl.exe http://localhost:28081/CrudView/index2.xhtml -I -c cookie -b cookie -v`
