### ISSUE TITLE
Add L10N resource (Japanese and Germany) additionally to the Admin Console

### ISSUE THREAD

**Issue by khasunuma** [payara/Payara#1713]
# Description #
----------

Since I had added L10N resource (see pull requests #346 and #361) in Payara 153, some new features have been added and there is not translated on admingui, especially Notification Service and Health Check configuration. I'd like to translate them to Japanese for most Japanese users and developers who is not familiar to English.

I believe additional L10N resource for Japanese is needed. However it for Germany is also useful if we can do. 

I currently use Japanese (it's my mother tongue) and English, thus translating English to Japanese is not difficult. But I can't translate English to Germany (I don't rely on machine translation yet).

My plan is:
* I'll translate additional L10N resources. My plan, I'll complete until Payara 174 release.
* For translate to Germany, my skill is lack. So I want to request it for someone can translation between English and Germany.

I think Japanese translation will start within a couple of days and send relational pull requests.

However, about Germany translation, I have few idea. please tell me 

If it's not a problem, then I want to promote it, I'll resolve it .
	
## Expected Outcome

Using payara-ml or payara-web-ml, some configuration screen shows English only.

## Current Outcome

Using payara-ml or payara-web-ml, some configuration screen adapt to L10N (especially, Japanese and Germany)

## Environment ##

- **Payara Version**: 4.1.2.172
- **Edition**: both Full and Web
- **JDK Version**: Oracle JDK 8, Zuru 8->
- **Operating System**: Windows (Proberbly happenon Mac and Linux)
- **Database**: None

**Comment by mikecroft** [comment]
At the moment we don't have much available bandwidth to properly support translations ourselves. It's on our radar and something we'd like to do, but we want to make sure we can support translations properly, so other languages can be kept up to date.

I'll close this issue for now, since it's a general request, rather than a request for a specific part of the server. We are very happy to accept PRs for translations of the admin console though! We are very grateful for the PRs you already submitted.
