### ISSUE TITLE
Option to disable "ejb-timer-service-app"

### ISSUE THREAD

**Issue by KriechelD** [payara/Payara#1803]
# Description #
----------

Running a stock Payara Server there is a default application deployed called "ejb-timer-service-app" which includes a web frontend at http://localhost:8080/ejb-timer-service-app/timer

More information here: https://docs.oracle.com/cd/E18930_01/html/821-2418/beahw.html

Sadly the frontend is not reachable over the protected admin console (port 4848) but over the main host (port 8080 and 8181). So everyone knowing my server URL can access this page.

It would be nice to have the possiblitiy to deactive the app (not the ejb-timer-service itself) within payara or at least make the frontend-page no longer accessable (hide it) so there is no need for some fancy firewall or loadbalancer configurations.

## Environment ##

- **Payara Version**: 4.1.2.172
- **Edition**: Full
- **JDK Version**:  8u141
- **Operating System**: All

**Comment by mikecroft** [comment]
I can see how this would be a security concern. I don't think we could change the app to be only available on port 4848, since that does not exist (by default) outside of the DAS. The app itself is just a WAR located in `${PAYARA_HOME}/glassfish/lib/install/applications/ejb-timer-service-app.war`. As a workaround, you could open this up and modify the web.xml to add some security constraints to the web page.

Alternatively, I think you could probably just remove the application from that location and deploy it yourself manually (i.e. through the admin console) before you deploy any timers. That way, you can manually add it to a new virtual server which exposes the web page only over the admin listener (port 4848).

**Comment by KriechelD** [comment]
Hey @mikecroft,
thanks for your fast reply. Does payara depend on this war file up and running? I don't realy get the purpose of this application, can it safely be removed at all? The information showing on the page are not mindblowing and I guess most people would search for those information somewhere in the admin console anyway. I would argue that most developers don't even know of that page, so did I^^

As an enhancement, maybe there is a way to show the counter of active timers somewhere in the admin console and remove the ejb-timer-service-app.war from the stock payara setup?

**Comment by mikecroft** [comment]
Yes, that WAR file is how the EJB timer service is implemented which we've inherited from GlassFish. We may just reimplement the timer service because having it implemented as a webapp is painful for maintenance. We've no firm plans around it yet, but I'm talking about it with engineers to work out what's the best kind of enhancement to raise for this issue...i.e. do we patch up the current issue and remove or hide the webpage, or do we roll that into a bigger enhancement of improving the whole timer service.

I'll let you know what decision gets made when I know it!

**Comment by KriechelD** [comment]
I did some quick tests locally on how to remove the frontend without damaging the EJB timer-service. Here is what I've changed inside the `${PAYARA_HOME}/glassfish/lib/install/applications/ejb-timer-service-app.war`:

Delete file `WEB-INF\sun-web.xml`
Delete file `WEB-INF\web.xml`
Delete folder `WEB-INF\classes\com`

After a domain restart the servlet at http://localhost:8080/ejb-timer-service-app/timer is no longer available (HTTP 404) nevertheless the EJB timers are working properly

**Comment by Andrew-Gr** [comment]
Just as another solution: as usually Payara is deployed behind reverse-proxy like Nginx, I just add the following lines to the Nginx config in order to disable access to the ejb-timer-service-app:
`
location /ejb-timer-service-app {
    return 404;
}
`

**Comment by fturizo** [comment]
Considering the nature of the enhancement and that the issue was reported for an older Payara Server version, we'll proceed to close it.
