### ISSUE TITLE
CDI should work without beans.xml

### ISSUE THREAD

**Issue by jerrinot** [payara/Payara#187]
Java EE 7 no longer requires beans.xml in order to active CDI. 

I have activated Hazelcast, but Payara doesn't seem to inject CacheManager to my servlet unless I explicitly create beans.xml.

I realize Payara documentation says:
> "You can also use Java annotations to access and use the CachingProvider and CacheManager embedded in Payara. Inject them into your application with CDI **(note, this requires at least one Bean to exist in your application)**"

However that's counter-intuitive and it may result in frustration of a developer. Besides that it doesn't say which type of bean has to exist. EJB? CDI? JSF? :) + it's not really true, it seems just an empty beans.xml is enough.

**Comment by smillidge** [comment]
This is because  the Jsr107 cdi extension does not get the before Bean discovery event.

The CDI spec defines an implicit bean archive as


"An implicit bean archive is any other archive which contains one or more bean classes with a bean defining annotation, or one or more session beans."

So you must contain a bean or a Session bean or add a beans.xml to initiate CDI and for injection to work.

**Comment by jerrinot** [comment]
I see. It's a bit counter-intuitive. Perhaps a warning/hint in a log would help? 

Also I think the documentation should suggest to create (empty) beans.xml as it's easier than trying to figure out what "Bean" one should create.

**Comment by smillidge** [comment]
It's not possible to log anything as CDI is not activated for your archive so the JSR107 CDI extension is not notified about your archive. 

Yep will add as a documentation bug.

**Comment by smillidge** [comment]
@Pandrex247 we need to modify the documentation to note that a CDI bean or session bean is required or a beans.xml file must be contained in the jar/war to ensure CDI is enabled.

**Comment by smillidge** [comment]
Documentation updated.
