### ISSUE TITLE
Single Jar Maven Dependency as in Payara Micro 4.1.1.164

### ISSUE THREAD

**Issue by nagaraja0yellapu** [payara/Payara#2060]
# Description #
----------
It was very easy to develop micro services using Payara Micro 4.1.1.164, post that we are forced to include eclipselink modelgen maven dependency that to version has to match which is included in Payara Micro. Similarly to use @NotEmpty hibernate validator api, we have to specify bean validation api maven dependency. Like that if we require eclipselink specific feature like **QueryHints**, ExceptionHandler, SessionCustomizer for multi tenant, we have to specify eclipselink dependency desperately along with Payara Micro dependency. For Jackson features as well, we have to include Jackson libraries for compilation of code. Similary for jersey-media-json-jackson as well.

## Expected Outcome

Single Payara Micro jar as maven dependency shall work as in version 4.1.1.64, that was what made consumers of Payara Micro a wow factor. There shall not be any necessity of inclusion of any library which is already included in Payara Micro.

## Current Outcome

Currently all the required maven dependencies along with Payara Micro have to included in the maven project.  As mentioned in some blogs / documentation Java EE 7 API maven dependency wouldn't be sufficient.

## Environment ##
Payara Version: 4.1.2.173

**Comment by cluxig** [comment]
I also identified this issue. The real problem is, that the payara-micro classloader created by `fish.payara.micro.boot.loader.Launcher.createClassLoader(URL[])` acts as a normal classloader, which asks the **parent-loader first** and the loader itself last. 
This breaks the documented way to start the payara via:
`PayaraMicro.getInstance().set[Any]().addLibrary()...bootStrap()`.

Easy way to reproduce: Add maven dependency `payara-micro:4.1.2.173`. Additionally add dependency `javax:javaee-web-api:7.0`. Deploy any working, external war using `fish.payara.micro.PayaraMicroRuntime.deploy(File)`, e.g. the payara-micro-example. It fails with missing javax.servlet resources, because they are not completely be part of javaee-web-api, but the classes around javax.servlet are loaded from this jar by app-classloader. In this case, the `payara-micro/MICRO-INF/runtime` jars are just skipped.

So yes, the documented way is working, as long as i don't touch the classpath dependencies or bring in exactly the same dependencies. But this is not a productive use-case.

For payara-launcher it would be easy to use a ParentLastClassLoader (or a completely isolated classloader), because all runtime jars are shipped by payara itself.

**Comment by smillidge** [comment]
Payara Embedded can be used for the same effect
