### ISSUE TITLE
Payara server get hung intermittently

### ISSUE THREAD

**Issue by sameencse** [payara/Payara#2222]
Payara server:
Payara Server  4.1.1.171 #badassfish

Moved my application from glassfish 3 to payra server  4.1.1.171
it was running successfully for almost 5 month now we observed the payara gets hung intermittently whenever the load increases. below is the server log

    **implementation=fish.payara.nucleus.requesttracing.RequestTracingService
        name=requesttracing-service
        contracts={fish.payara.nucleus.requesttracing.RequestTracingService,org.jvnet.hk2.config.ConfigListener}
        scope=org.glassfish.hk2.runlevel.RunLevel
        qualifiers={}
        descriptorType=CLASS
        descriptorVisibility=NORMAL
        metadata=runLevelValue={10},Bundle-SymbolicName={fish.payara.payara-modules.requesttracing-core},Bundle-Version=_{4.1.1.171_0_1}_
        rank=0
        loader=OsgiPopulatorPostProcessor.HK2Loader(OSGiModuleImpl:: Bundle = [fish.payara.payara-modules.requesttracing-core [224]], State = [READY],1141584589)
        proxiable=null
        proxyForSameScope=null
        analysisName=null
        id=1159
        locatorId=0
        identityHashCode=1722949691
        reified=true)
]]**

Please suggest what is causing this issue?

**Comment by smillidge** [comment]
171 is an old version have you tried with later versions?

**Comment by mikecroft** [comment]
Hello @sameencse - the log snippet you posted is not relevant and does not help with diagnosing any problem. Since 171 is almost a year old now, I will close this issue until we have confirmation of the same problem in the latest current release.

If you require support for old versions like 171, please get in touch with us about a support contract:
https://www.payara.fish/support
