### ISSUE TITLE
Libraries not backed up and restored

### ISSUE THREAD

**Issue by DaveJarvis** [payara/Payara#2280]
# Description #
----------

Backing up a Payara instance does not bundle libraries added into the "lib" directory. Replicate:

## Expected Outcome

The /opt/payara/glassfish/lib directory contains postgresql-42.1.4.jar.

## Current Outcome

The /opt/payara/glassfish/lib directory does not contain postgresql-42.1.4.jar.

## Steps to reproduce (Only for bug reports) 

1. Download PostgreSQL JDBC driver.
1. Install driver into /opt/payara/glassfish/lib
1. Create a backup using asadmin.
1. Install a new Payara instance.
1. Restore backup into new instance.

## Environment ##

- **Payara Version**: 4.1 and 5.0 beta 1
- **Edition**: Full
- **JDK Version**: 8 u151
- **Operating System**:  Linux
- **Database**: PostgreSQL

**Comment by mikecroft** [comment]
Hi @DaveJarvis - this is expected behaviour. The backup and restore operations relate specifically to the *domain* specified, whereas this lib directory is not intended for use with drivers.

Payara Server is set up so that *all* user configuration should live in the domain directory. This is because many domains can be started and run by the same Payara Server code, so it's bad practice to keep libraries in a place which can affect multiple domains. The correct way to add libraries is to use `asadmin add-library` which will place the library in the `domain-dir/lib` directory, ensuring that it will be backed up correctly and not interfere with any other domain.

Here is a sample of the help page for the command for more information:

```
➜  5.181 bin/asadmin help add-library
add-library(1)            asadmin Utility Subcommands           add-library(1)

NAME
       add-library - adds one or more library JAR files to GlassFish Server

SYNOPSIS
           add-library [--help] [--type={common|ext|app}] [--upload={false|true}]

           library-file-path [library-file-path ... ]

DESCRIPTION
       The add-library subcommand adds one or more library archive files to
       GlassFish Server.

       The --type option specifies the library type and the GlassFish Server
       directory to which the library is added.

       The library-file-path operand is the path to the JAR file that contains
       the library to be added. To specify multiple libraries, specify
       multiple paths separated by spaces.

           Note
           +----------------------------------------+
           |           The library archive file is  |
           |           added to the DAS. For common |
           |           and extension libraries, you |
           |           must restart the DAS so the  |
           |           libraries are picked up by   |
           |           the server runtime. To add   |
           |           the libraries to other       |
           |           server instances,            |
           |           synchronize the instances    |
           |           with the DAS by restarting   |
           |           them.                        |
           +----------------------------------------+

       This subcommand is supported in remote mode only.

OPTIONS
       --help, -?
           Displays the help text for the subcommand.

       --type
           Specifies the library type and the GlassFish Server directory to
           which the library is added. Valid values are as follows:

           common
               Adds the library files to the Common class loader directory,
               domain-dir/lib. This is the default.

           ext
               Adds the library files to the Java optional package directory,
               domain-dir/lib/ext.

           app
               Adds the library files to the application-specific class loader
               directory, domain-dir/lib/applibs.

           For more information about these directories, see "Class Loaders"
           in Oracle GlassFish Server Application Development Guide.

       --upload
           Specifies whether the subcommand uploads the file to the DAS. In
           most situations, this option can be omitted.

           Valid values are as follows:

           false
               The subcommand does not upload the file and attempts to access
               the file through the specified file name. If the DAS cannot
               access the file, the subcommand fails.

               For example, the DAS might be running as a different user than
               the administration user and does not have read access to the
               file. In this situation, the subcommand fails if the --upload
               option is false.

           true
               The subcommand uploads the file to the DAS over the network
               connection.

           The default value depends on whether the DAS is on the host where
           the subcommand is run or is on a remote host.

           *   If the DAS is on the host where the subcommand is run, the
               default is false.

           *   If the DAS is on a remote host, the default is true.

           If a directory filepath is specified, this option is ignored.

OPERANDS
       library-file-path
           The paths to the archive files that contain the libraries that are
           to be added. You can specify an absolute path or a relative path.

           If the --upload option is set to true, this is the path to the file
           on the local client machine. If the --upload option is set to
           false, this is the path to the file on the server machine.

EXAMPLES
       Example 1, Adding Libraries
           This example adds the library in the archive file mylib.jar to the
           application-specific class loader directory on the default server
           instance.

               asadmin> add-library --type app /tmp/mylib.jar
               Command add-library executed successfully.

EXIT STATUS
       0
           subcommand executed successfully

       1
           error in executing the subcommand

SEE ALSO
       remove-library(1), list-libraries(1)
```

**Comment by DaveJarvis** [comment]
Consider, then:

* removing the global `lib` directory;
* adding an option to back up the common `lib` directory; or
* display a warning to the user (stderr) that there are files in the `lib` directory that are not backed up.

Conceptually, a "backup" and "restore" means "back up the current application state and restore it so that it is functional on the new web application server." By not backing up the `lib` directory, nor providing any indication that the `lib` directory won't be restored, it is a minor violation of the principle of least astonishment:

> "People are part of the system. The design should match the user's experience, expectations, and **mental models**."

**Comment by mikecroft** [comment]
Hi @DaveJarvis,

> removing the global lib directory;

This is not feasible since the directory is used by Payara Server. The server itself needs somewhere to put its own libraries and `lib` is a standard name for such a directory. User `lib` directories must be kept separate from the server's `lib` directories to avoid unintended consequences by user actions, such as accidental deletion.

> adding an option to backup/restore the common lib directory;

All the user lib directories are contained within the domain and are therefore backed up by the `backup-domain` and `restore-domain` commands. These commands and their behaviour are explained in detail in the documentation.

> displaying a warning to the user (stderr) that there are files in the lib directory that will not be backed up; or
> detecting when files are in the lib directory and suggesting to the user that the add-library command be used instead.

[These recommendations are made clearly in the documentation](https://javaee.github.io/glassfish/doc/5.0/administration-guide.pdf). Since Payara Server inherits from GlassFish, our own documentation covers [backup](https://docs.payara.fish/documentation/user-guides/backup-domain.html) and [restore](https://docs.payara.fish/documentation/user-guides/restore-domain.html) from a task-oriented perspective

>Conceptually, a "backup" and "restore" means "back up the current application state and restore it so that it is functional on the new web application server." By not backing up the lib directory, nor providing any indication that the lib directory won't be archived, it is a minor violation of the principle of least astonishment in that the application won't be functional when restored:
>
> > "People are part of the system. The design should match the user's experience, expectations, and mental models."

I agree with your definition of backup and restore, but I disagree that this particular case violates the principle of least astonishment due to the fact the commands are specifically named `backup-domain` and `restore-domain`. It seems reasonable to me to assume that the commands specifically concern the ***domain*** (i.e. user configuration) rather than the installation files. This is also similar to the behaviour of other Java application servers such as IBM's OpenLiberty or WildFly.

Additionally, each command has a documented help function which should leave the user in no doubt as to its purpose.

It's not possible to link directly to content in a PDF, but archive documentation for GlassFish is still readily available and easy to find through Google. This documentation clearly states:

> When you use the backup-domain subcommand, GlassFish Server creates a ZIP file backup of all the files and subdirectories in the domain's directory, domain-root-dir/domain-name, except for the backups subdirectory.

https://docs.oracle.com/cd/E18930_01/html/821-2416/gityo.html
