### ISSUE TITLE
Release Versioning Scheme

### ISSUE THREAD

**Issue by thomas-mc-work** [payara/Payara#2405]
So far every Payara release is depending on the upstream Glassfish release. From my point of view it's getting a bit messy in the situation when Glassfish is releasing a point release. For example the `5.x` series starts with Glassfish `5.0` and the derived version Payara `5.181`. Now when Glassfish is releasing `5.1` then Payara is forced to virtually downgrade the version number to `5.1.181`. So this confuses the sorting of the semantic versioning scheme (and my personal intention too).

What about following the debian model by simpy seperating the upstream and the downstream version numbers by a dash. So Payara would become `5-181`, `5-182` or later `5.1-182`.

@see https://www.debian.org/doc/debian-policy/#version

**Comment by mikecroft** [comment]
Hi @thomas-mc-work - Payara 5 breaks compatibility with GlassFish somewhat, which is why we have changed the version number scheme.

Going forward, we will no longer track the GlassFish minor version numbers since they are no longer relevant. Indeed, even version 4.1.2 from GlassFish included so little it did not seem worth the increment. From Payara 5, we will only add Payara specific version numbers following the initial "`5.`"

Does that answer your question?

**Comment by thomas-mc-work** [comment]
Yes, that's a way to round the problem  :thumbsup:
