### ISSUE TITLE
Add cacerts truststore update to payara delivery process

### ISSUE THREAD

**Issue by hypn0toast** [payara/Payara#2441]
# Description #
----------

The truststore file distributed with payara4 is way outdated.

## Expected Outcome

Each distributed version of payara should ship with an update truststore file located in ${com.sun.aas.instanceRoot}/config/cacerts.jks

The proposal is to add a step in the delivery process which updates the truststore file included in the distribution.

## Current Outcome

The shipped truststore file wasn't updated since late 2009.
Connecting via SSL using CA certificate chains issued from 2010 on will fail and requires to update the payara-included truststore manually.

Also see #2312

## Steps to reproduce (Only for bug reports) 

n.a.

### Samples

n.a.

## Context (Optional)

Was trying HTTPS requests towards a domain resulted in
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

## Environment ##

- **Payara Version**: 4.1.2.173
- **Edition**: Full
- **JDK Version**: 8u162 - Oracle
- **Operating System**: Linux
- **Database**: MariaDB

**Comment by mikecroft** [comment]
Hi @hypn0toast - as the PR you linked suggests, this has been fixed in the next version of Payara which is due to be released very shortly. There will be no further public releases of Payara 4.x, though our customers will continue to receive updates.

If your business already has support, then you should have access to all these builds; please get in touch if you need help downloading them or contact us at sales@payara.fish if you would like support.

**Comment by hypn0toast** [comment]
Hi @mikecroft, sorry for creating this duplicate but from reading #2312 it wasn't clear to me if this was  added to the delivery process or was just a one-time update done to payara5.
Keep up the great work and thanks for the quick response.
