### ISSUE TITLE
Payara java.lang.String objects probably memory leak

### ISSUE THREAD

**Issue by scrmtrey91** [payara/Payara#2562]
We discovered (quite a while ago) probably some payara server memory leak (java.lang.String objects just grow unlimited, until GC steps in). Graph provided below is recorded RAM from payara server. This is also confirmed by diagnostic tool like JMeter and some others. 

Payara version: I don't think its version related, because this was happening on previous versions as well.

This is happening even on fresh start of payara with default domain.xml and no WAR, EAR deployed on payara server.

![ram_tl](https://user-images.githubusercontent.com/24773401/37817471-31935a06-2e77-11e8-96c3-0650daf86820.PNG)

I don't know if this is normal behaviour of payara server or a memory leak (but it is weird for sure).

**Comment by mikecroft** [comment]
I would be very surprised if there was a memory leak like this due to the number of users of Payara Server who have not seen or reported anything like this.

It could be a leak in your application, but I don't think that's necessarily correct either. It's hard to say from the graph without any scale on it, but that doesn't look like memory leak behaviour to me. It does look very, very strange though.

Often, the parallel collector will produce a sawtooth-like pattern in GC logs, but the near vertical edge is usually the **trailing** edge, not the **leading** edge. Here, it seems like memory usage climbs dramatically, before gradually reducing.

You say that your diagnostic tool was JMeter - how did you use it? Were you load testing an empty Payara Server? How was the graph produced? Is it from actual GC.logs? What was the GC policy?

**Comment by scrmtrey91** [comment]
Like i said it happens even with empty payara server without a single app deployed on server.
The same thing can be seen on JProfiler. 

You just attach to JVM thread that payara is running and observe the results.
This graph was draw with another app with vaadin charts. It is collected from payara server like this:

 java.lang.Runtime
 Runtime runtime = Runtime.getRuntime();
        ramStatus.setMaxMemory(runtime.maxMemory());
        ramStatus.setTotalMemory(runtime.totalMemory());
        ramStatus.setFreeMemory(runtime.freeMemory());
        ramStatus.setLocalDateTime(LocalDateTime.now());

But it is 1:1 with JProfiler when numbers of String objects just grow and grow and then GC do the job to clean unused String objects.

**Comment by mikecroft** [comment]
Seeing large numbers of strings or char[] or byte[] or similar before the GC clears them up is perfectly normal. What makes it a memory leak is if the GC ***can't*** clean them up.

**Comment by scrmtrey91** [comment]
Ok then, thanks for explanation. We just did not know if this is normal or not. So this should not affect on free memory for war deployed application to use. 

Yeah i know "stuck object with reference which are not used". We just could not explain this behaviour. But i guess we can be calm about this one. 

Thanks for response.

**Comment by mikecroft** [comment]
No problem. I think the way you are gathering your data is very misleading, though. Accurate data will be in your gc.log and will contain details of when GC is occurring and how long it's taking, which is a much better indication of health. You can then analyse it with something like [GCViewer](https://github.com/chewiebug/GCViewer).

For memory leaks, the thing to watch out for is the ***valleys*** not the ***peaks*** in those graphs. It's very normal for heap usage to get very close to 100%, before the GC happens and clears things down to a low level. The problem occurs when the low usage that the GC clears down to gradually increases over time.

Even that might not necessarily be a leak - it may simply be heap exhaustion if you were doing something like loading very large amounts of data into memory, it might be too much for the JVM to handle.

At that point, it's time to collect a heap dump and start the detailed investigation!
