### ISSUE TITLE
Context root defined in glassfish-web.xml always gets overridden when deployed via browser UI

### ISSUE THREAD

**Issue by scrmtrey91** [payara/Payara#2619]
# Description #

We decided to change names for our war files (add version). But we still need the old context root of the application (because of internal calls inside IS).

We created test app with glassfish-web-xml in webapp/WEB-INF folder with structure:
 
```
<!DOCTYPE glassfish-web-app PUBLIC "-//GlassFish.org//DTD
GlassFish Application Server 3.1 Servlet 3.0//EN"
        "http://glassfish.org/dtds/glassfish-web-app_3_0-1.dtd"> 
<glassfish-web-app>
    <context-root>ApplicationAccess</context-root>
</glassfish-web-app>
```

## Expected Outcome

When deployed on server, the context root should set correcly to defined  value in xml deployment descriptor if exist (via browser ui or via asadmin).

## Current Outcome

When deployed on server via browser UI, it should automaticaly set context root value from xml deployment descriptor. But it does not.
`Loading application [TestApp-1.0.0] at [/TestApp-1.0.0]]]`

When deployed via intellij (maven asadming) it does work as excpected (context root is set correcly as defined in xml file). 
`Loading application [TestApp-1.0.0] at [/ApplicationAccess]]]`

**Comment by dmatej** [comment]
I would not be so rude, but I agree this descriptor is not too "usage friendly". Documentation is unavailable (this is not enough: https://docs.oracle.com/cd/E18930_01/html/821-2417/beaql.html#scrolltoc ), some elements are duplicated, and their meaning is not clear. It should be revised and perfectly documented - and maybe new xsd/dtd should be released.

I had a problem with arquillian deployments too because the context root changed with each version (version is a part of the name of the artifact). Finally I had to change the filename of the deployed archive  `ShrinkWrap.create(WebArchive.class, "ec.war")` so the context is `/ec` now.

**Comment by matthiasblaesing** [comment]
@lprimak is right - the GUI guesses the context root from the war name. However having an option in the GUI to let it take the values from the war deployment descriptor instead of the GUI fields would be helpful. I routinely see badly deployed applications at work because the developer does not notice the broken name. Of course this could be mitigated by using the `asadmin` command (that uses the deployment descriptor unless explicitly asked to override the values), but then the web gui is convenient.

**Comment by phillipross** [comment]
I realize that the use case is that the contextroot is predfined and declared within the archive itself, but additionally, asadmin lets you specify the contextroot on the commandline with the --contextroot param.  I think you can also change the contextroot for a deployed app with the `asadmin set` command, but I've never tried it before.

**Comment by lprimak** [comment]
The deployment descriptor is targeted at scripted deployment via asadmin, to make the deployment more usable and more consistent.  It is not targeted at UI deployment.
UI currently does not read the contents of WAR files and fill in the appropriate UI fields, it just guesses them from the name.  It would be a lot of work of dubious usefulness, and would slow down the GUI.
In my view this isn't a useful feature unless asked by a support customer

**Comment by smillidge** [comment]
I think consistency would be good across asadmin and the console but as you say it could be a lot of work.

**Comment by scrmtrey91** [comment]
At least could be option in the UI via browser:

Checkbox:
- Override deployment descriptor (yes / no)

Result:
- If yes, then it uses the value from textfield like now
- If no, first check deployment descriptor (in the progress of deploying), if it does not exist it take context root from war file name


I don't know if this is too hard or impossible to do in application server. But just an idea.

**Comment by lprimak** [comment]
That’s certainly possible. Also a blank value could be used for the same purpose. 
Would a blank value solution work for you @scrmtrey91 ?

**Comment by scrmtrey91** [comment]
What do you mean by blank value ?


When you select war to deploy, it would be blank value instead of prefilled one from war file?

If you leave blank value, it try to read from deployment descriptor ? If not found it still takes the war file name for context root ?

When filled instead of blank value, it uses this filled value for context root ?

**Comment by lprimak** [comment]
Yes, that sounds reasonable to me

**Comment by scrmtrey91** [comment]
Ok sound good. So default is always blank value ?

Will this "fix" be in the next version or we need to wait a little longer?

**Comment by lprimak** [comment]
Yes, the default would always be blank value.
Not sure when the fix will be scheduled.  You can watch this issue for pull request

**Comment by scrmtrey91** [comment]
OK thanks for your time and patience. We are looking forward to use this when it will be available. 

Have a nice day.

**Comment by lprimak** [comment]
you are welcome

**Comment by lprimak** [comment]
Created internal issue ```PAYARA-2697```
