### ISSUE TITLE
Bug on click Enable Secure Admin button

### ISSUE THREAD

**Issue by luongdangdung** [payara/Payara#275]
Steps to reproduce:

1. unzip payara-4.1.152.zip
2. cd payara41/bin
3. ./asadmin start-domain domain1
4. Go to browser, http://localhost:4848
5. Set admin password 
6. On server node, click button **Secure Administration**

Actual result: it notify **An error has occurred**, after that click on button **Enable Secure Admin** will redirect to error page

Expected result: no message appear, and click button **Enable Secure Admin** work properly.

**Comment by Pandrex247** [comment]
Looks like this was caused by the changes brought in from upstream in #235, specifically the Jersey 2.16 upgrade commit 8b393fe. Possibly related to #269, as this also throws a `null` exception: first when trying to call the aliases `s1as` and `glassfish-instance` to fill out the text fields; and again when trying to enable the secure admin.

**Comment by luongdangdung** [comment]
I tried the way that you suggest, but the bug still occurs (same first post)

**Comment by luongdangdung** [comment]
I think this bug is small but it make me can not bring system to production because admin web interface can not be secured.

Should I back to Payara 4.1.151 or wait to get hot fix of 4.1.152?

**Comment by smillidge** [comment]
Command line asadmin enable-secure-admin works still to secure the web interface. It is user interface problem only.
