### ISSUE TITLE
Feature Request: start-domain should not fail, when domain is started /CUSTCOM-140

### ISSUE THREAD

**Issue by deratzmann** [payara/Payara#3051]
# Description #
----------
We use payara full in production.
As a requirement from our Security department, we are not allowed to store passwords in plain text anywhere in container files.
Further we have to use a keycloak server to fetch all access data for e.g. databases, jms queues etc.

Because of using immutable images for every environment (dev, test, production) we first know, which connection data to fetch at server startup time. the outcome is a docker entrypoint definition like this:
`ENTRYPOINT echo "Starte $application: $(date)" && \
            /opt/payara/bin/asadmin start-domain && \
            bash /opt/getCredentialsFromKeycloak.sh ${ENVIRONMENT} && \
            /opt/payara/bin/asadmin deploy --force --skipdsfailure true ${DEPLOYMENT_DIR}/${application}.war && \
            tail -f -n +1 /var/log/${HOSTNAME}/server.log`

the tail command (tail -f) is the process that makes the current container live.

With the recommended `start-domain -v --postbootcommandfile deployapp.cli` this does not work, because the connection data must be dynamically fetched.

My suggestion would be:
create a flag for start-domain, that this command does not fail, when the domain is currently running.

so our Entrypoint would be like this:
`ENTRYPOINT echo "Starte $application: $(date)" && \
            /opt/payara/bin/asadmin start-domain && \
            bash /opt/getCredentialsFromKeycloak.sh ${ENVIRONMENT} && \
            /opt/payara/bin/asadmin start-domain -v --donotquitwhenrunning --postbootcommandfile deployapp.cli`

## Environment ##

- **Payara Version**: 5.182
- **Edition**: Full
- **JDK Version**: 8 openjdk
- **Operating System**: linux
- **Database**: oracle

**Comment by rdebusscher** [comment]
Hi,

I have created `CUSTCOM-140` for this feature request.

But I'm not sure why this solution is not working for you

`ENTRYPOINT echo "Starte $application: $(date)" && \ /opt/payara/bin/asadmin start-domain && \ bash /opt/getCredentialsFromKeycloak.sh ${ENVIRONMENT} && \ /opt/payara/bin/asadmin start-domain -v --postbootcommandfile deployapp.cli`

Because with a Docker Container you controls exactly when a Payara domain is started.

You can always use environment references in your database, JMS queue, etc ...   connection definitions (see https://docs.payara.fish/documentation/payara-server/server-configuration/var-substitution/usage-of-variables.html) 

Regards
Rudy

**Comment by AlanRoth** [comment]
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.
