### ISSUE TITLE
Temporary patch for the SSL error with JDK 8u191 (sun.security.ssl.SSLSessionImpl)

### ISSUE THREAD

**Issue by RejDev** [payara/Payara#3296]
Hello,

The problem is that Glassfish embeds an old version of the SUN implementation without (sun.security.ssl.SSLSessionImpl)

I found a solution to solve the problem temporarily (issue :  #3284  ).

```
1) go to path : $JDK_HOME$ /jre/lib/
1.1) copy this file : /jsse.jar

2) go to path : $PAYARA5_INSTALL$/glassfish/lib/
2.1) backup : grizzly-npn-bootstrap.jar

3) open "jsse.jar" with an archive editor
3.1) go to path (in archive) : sun/security/ssl
3.2) extract folder "ssl"

4) open "grizzly-npn-bootstrap.jar" with an archive editor
4.1) merge the "ssl" folder extracted from the "jsse.jar" archive with the "ssl" folder
       into "grizzly-npn-bootstrap.jar", overwriting the files with the same name

5) restart payara.
and normally everything works properly
```
Or use this modified file :
https://www.sendspace.com/file/es8sj0
and replace the original file here : $PAYARA5_INSTALL$/glassfish/lib/
(do not forget to make a backup)

Have a good day..

_Originally posted by @RejDev in https://github.com/payara/Payara/issues/3284#issuecomment-431535842_

**Comment by MattGill98** [comment]
Hi @RejDev,

Thank you for your suggested fix. This issue has already been raised in #3284, and fixed in https://github.com/javaee/grizzly-npn/commit/4082270305299046043f5344c62ecb6d4f0678d0. We will be making a backport of this issue and including it in 5.184. Since the status of this can be updated in the aforementioned issue, I'll close one.

Kind regards,

Matt
