### ISSUE TITLE
Inconsistent metrics time units 

### ISSUE THREAD

**Issue by renvo** [payara/Payara#3883]
Description 
When using injected Timer Metric, the chosen Metric units are not respected.

----------
When using:

@Inject
@Metric(name= "TestTimer", unit = MetricUnits.MILLISECONDS, description="test")
private Timer testTimer;
...
testTimer.update(1000, TimeUnit.MILLISECONDS);

## Expected Outcome

When using the metrics url: .../metrics/application

Should show:
  TYPE application:test_test_test_timer_max_seconds gauge
application:test_test_test_timer_max_seconds 1.0

## Current Outcome

  TYPE application:test_test_test_timer_max_seconds gauge
application:test_test_test_timer_max_seconds 1000000.0

## Environment ##

- **Payara Version**: payara-micro-5.184
- **Edition**: Micro
- **JDK Version**: 8 - OpenJDK
- **Operating System**: alpine Linux

**Comment by smillidge** [comment]
Can you create a simple maven project that reproduces the issue.

**Comment by vlumi** [comment]
I created a simple web project where I can reproduce this issue: https://github.com/vlumi/timertest

With the following piece of code (called when accessing index.xhtml):
```
@ApplicationScoped
public class TestLogic {
    @Inject
    @Metric(name = "TestTimer", unit = MetricUnits.MILLISECONDS, description = "test")
    private Timer testTimer;

    public String getText() {
        testTimer.update(1234, TimeUnit.MILLISECONDS);
        return "Hello, world!";
    }
}
```
All of the timers at `/metrics/application` are off by six magnitudes, e.g.:
```
application:fi_misaki_testtimer_test_logic_test_timer_mean_seconds 1234000.0
```

With `MetricUnits.SECONDS`, the magnitude increases by three:
```
application:fi_misaki_testtimer_test_logic_test_timer_mean_seconds 1.234E9
```

It seems that I can only get the expected outcome if with `MetricUnits.NANOSECONDS`:
```
application:fi_misaki_testtimer_test_logic_test_timer_mean_seconds 1.234
```

Is it intentional that the unit baseline is nanoseconds and the time unit for update() is shifted accordingly? It's confusing at least, as I would expect the time unit passed to update() to be absolute.

Tested on Payara 5.192.

**Comment by vlumi** [comment]
Created PR #4044 for a fix.

This appears to only affect the `text/plain` output -- `application/json` always outputs in ns.

The internally stored time is always in ns, and the output is hard-coded to seconds, so the (broken) logic to use the `unit` is unnecessary.

It's unclear if the output should actually use the `unit`, but as all time-based units are normalized to seconds (in the text), I left that as-is.

**Comment by jGauravGupta** [comment]
Created internal ticket **PAYARA-3933** to address it.
