### ISSUE TITLE
Docker payara 5.184 : Set jvm javaagent ignored:  -javaagent:${com.sun.aas.instanceRoot}/lib/spring-instrument-5.1.5.RELEASE.jar

### ISSUE THREAD

**Issue by DNWEIJ** [payara/Payara#4056]
Running the docker version of payara 5.184.
Adding the jvm javaagent via the gui, is not accepted after restart, when application.war is deployed. error is given: 
`IllegalStateException: Must start with Java agent to use InstrumentationLoadTimeWeaver`

**What did i do:**
*create dockerfile*
```
FROM payara/server-full:5.184
# Setup configuration
USER payara
COPY libs/spring-instrument-5.1.5.RELEASE.jar /opt/payara/appserver/glassfish/domains/production/lib
```

run:
`docker build --tag=mydockerhost .`
start docker.
Go to admin UI. Add JVM property -javaagent:${com.sun.aas.instanceRoot}/lib/spring-instrument-5.1.5.RELEASE.jar
restart
Deploy application.war 
Getting error.

**What did I validate:**
I checked the lib file being there and loaded in the docker image while it was running. 
Check what happens when i dont put in the jar files; If i don't deliver the file i get an error, so adding it will ensure it is there (no error is given).  
I checked if the domain.xml had the jvm setting in the running docker image
I checked via docker exec in the actual docker image

**validation on normal install**
I downloaded  payara 5.184  (traditional not the  docker)
installed payara (unpack zip)
start and add JVM property
restart
install application.war
all is good, no error is given. 

Any ideas?

**Comment by OndroMih** [comment]
This isn't a supported scenario in Docker. Because docker containers are ephemeral, they should be configured before you run them or during boot with post boot command files that run asadmin commands. Docker isn't supposed to behave exactly like Payara Server installed traditionally and you shouldn't configure Payara Server in Docker via Admin Console.

You can enable the Asadmin recorder in your traditional Payara Server installation, configure it as you need and then copy the asadmin commands to the Docker container into a post boot command file. 

In case of JVM options, they need to applied even before Payara Server is started, so you need to apply them either using pre-start scripts, or during Docker image build time in Dockerfile - run Payara Server, execute the `create-jvm-options` asadmin command, then stop Payara Server.
