### ISSUE TITLE
Payara Server Full + MicroProfile Config + Enviroment Variables

### ISSUE THREAD

**Issue by Motojo** [payara/Payara#4189]
# Description #
----------

Using Para Server full and MicroProfile Config, the environment variables are not mapped ultil a server restart.

## Expected Outcome

If a war is deployed, it should map the environment variables to MicroProfile config properties without a server restart.

## Current Outcome

MicroProfile Config keeps using local config values (microprofile-config.properties) until a full server restart occurs.

## Steps to reproduce (Only for bug reports) 

1. Start Payara server full
2. Deploy an application that uses MicroProfile Config and has a micrprofile-config.properties file
3. Create environment variables that should override the MicroProfile config values.
4. Re-deploy the application to Payara server Full (with o whithout changes)
5. Application keeps using microprofile-config.properties values.
6. Restar Payara server full
7. Application now uses the values from environment variables.

## Environment ##

- **Payara Version**: 5.192
- **Edition**: Full
- **JDK Version**: Zulu JDK 8.40 (1.8.0_222)
- **Operating System**: Ubuntu Linux

**Comment by smillidge** [comment]
We need a reproducible test case. Overriding of variables when using MP Config will also depend on how you inject the variable for example if you inject it into an ApplicationScoped Bean then that variable will be fixed for the duration of the deployment, if you inject into a Request Scoped Bean then the value will be injected new on every request.

**Comment by Motojo** [comment]
Sorry for late response, I will create a reproducible test case / video this weekend.
Thanks!

**Comment by OndroMih** [comment]
Hi, did you have time to create a reproducible test case for us? Unless we get a reproducer soon, we'll need to close this issue.

**Comment by Motojo** [comment]
Hello!
Sorry for being non responsive, I have a lot of work 😅 

I just recorded a [video](https://youtu.be/5jzSZgNEUqs) demonstrating my issue with the MicroProfile Config API.
Also I tested it on Payara 5.194 and MicroProfile 3.2


Thanks!

**Comment by OndroMih** [comment]
Hi @Motojo, in the video you define the environment variable after you started Payara Server. Environment variables are not like Java system properties, you can't redefine them once the process is started. They are only inherited from the current terminal when Payara Server is started.

So, to configure MP property using Environment variables, you need to define the variable before you start Payara Server AND in the same terminal.

Environment variables are not very convenient in your usecase. Using environment variables is mostly useful only in Docker environments or environments that rarely change their configuration (e.g. dev,test,prod pipeline).

In your case, I would rather define the MP property using Java system properties, which can be redefined during runtime. You just have to define them as system properties for the server/instance and not via JVM command line options because then they would again be evaluated only when Payara Server is started.

I'm closing this issue as it's not a bug but expected behavior that we can't do anything about.
