### ISSUE TITLE
Allow steady pool size with 0 again

### ISSUE THREAD

**Issue by deratzmann** [payara/Payara#4197]
# Description #
----------
For our test environments we create connection-pools for a postgres DB which might not be available. Therefore to avoid errors while startup we created the pools with a steady size of 0.
here is the cli file:
`create-jdbc-connection-pool --validateatmostonceperiod=5 --creationretryattempts=3 --creationretryinterval=20 --maxwait=2000 --datasourceclassname org.postgresql.ds.PGConnectionPoolDataSource --restype javax.sql.ConnectionPoolDataSource --isconnectvalidatereq true --validationmethod auto-commit --steadypoolsize 0 --maxpoolsize 30 --poolresizequantity 15 --idletimeout 3600 --leakreclaim false --statementtimeout 60 --leaktimeout 120 --statementleakreclaim=false --statementleaktimeout 30 --failconnection false --property user="${DAYSNAP_username}":password="${ALIAS=daysnap_password}":url="${DAYSNAP_url}":characterEncoding="UTF-8":ssl="true":sslmode="verify-ca" DAYSNAP2`

Expected: successfully created connectionpool.

Current:
`$ ./asadmin -p 1048 multimode --file t.txt
remote failure: JDBC connection pool DAYSNAP2 creation failed. Constraints for this JdbcConnectionPool configuration have been violated: on property [  ] violation reason [ Max-pool-size has to be greater than or equal to steady-pool-size ]
Command create-jdbc-connection-pool failed.
Command multimode failed.
`
If I change steadypoolsize to 1, it works.
So is this a bug or a new constraint?

## Environment ##

- **Payara Version**: 5.193
- **Edition**: Full
- **JDK Version**: Openjdk 8
- **Operating System**: windows
- **Database**: Postgres

**Comment by rdebusscher** [comment]
Hi @deratzmann 

There is indeed now a check on the value of Max Pool Size and Steady Pool Size that it can't be 0 or smaller (but without the correct error message)

This is the code added in 5.193
https://github.com/payara/Payara/commit/eec452eed1d3da01ffc9a428dad38b1d0c33138d#diff-95dc2efc07f48f0d9760406d695c3e06R140

I have created the internal issue PAYARA-4205 to correct the error message. But I agree with the change because a pool size of 0 doesn't make much sense.

The create command will succeed even when the database is not up, only deployment of applications will fail if they access the JDBC pool and database cannot be contacted.

**Comment by sergitrujillo** [comment]
Hi everyone,

A simple suppose that you have a database with 20 schemas that they no is usually accessed but you need to have config 20 pools. Your system are always maintain 20 connections in use and it could be so expensive if the model of billing of this is by connection.

I propouse that simply remove the equal part of conditon : 
141:  steadyPoolSizeValue <= 0  should be  steadyPoolSizeValue < 0.

thank you.

**Comment by dmatej** [comment]
Hi, sorry for that, fix did not make it to brand new 5.194, which should be released soon, but we already have an internal issue for that, so I am pretty sure it will be fixed in next community release.

**Comment by rdebusscher** [comment]
The fix for this will be shipped in version 5.201
