### ISSUE TITLE
Why my schedule is executed twice

### ISSUE THREAD

**Issue by peterpz1** [payara/Payara#4236]
# Description #
----------

My schedule is described this way:

Class:
```
@Singleton
@Startup
@Slf4j
public class PsVideoDataDownloader extends AbstractTrigger {
```

And task:
```
@Schedule(second = "0", minute = "0", hour = "14", persistent = false)
    public void execute() {
        log.debug("execute");
}
```

## Expected Outcome

Method run only at 14:00.

## Current Outcome

Method is running as specified:
```2019-09-22 14:00:00.002 [__ejb-thread-pool6] DEBUG pl.orangelabs.pms.triggers.ps.video.PsVideoDataDownloader - execute```

It takes to do the job 13 minutes, after end there is a warning in server log:
```[2019-09-22T14:13:41.125+0200] [Payara 5.193] [WARNING] [] [javax.enterprise.system.container.ejb.com.sun.ejb.containers] [tid: _ThreadID=279 _ThreadName=__ejb-thread-pool6] [timeMillis: 1569154421125] [levelValue: 900] [[
  EJB5123:Rolling back timed out transaction [JavaEETransactionImpl: txId=11 nonXAResource=1919 jtsTx=null localTxStatus=1 syncs=[com.sun.ejb.containers.SimpleEjbResourceHandlerImpl@787d10a3, com.sun.ejb.containers.ContainerSynchronization@6b6dea9, com.sun.enterprise.resource.pool.PoolManagerImpl$SynchronizationListener@45ee6ca0]] for [PsVideoDataDownloader]]]
```

And the method is called second time:
```2019-09-22 14:13:46.127 [__ejb-thread-pool7] DEBUG pl.orangelabs.pms.triggers.ps.video.PsVideoDataDownloader - execute```

Why? I didn't specify it to run at 14:13:46. And also what to do when method is lasting such a long time? Maybe there is some timeout in transaction and rollback is causing the second call but in my opinion it shouldn't.

## Steps to reproduce (Only for bug reports) 

Define the code as described earlier, make method run 13 minutes and it will be called again.

## Environment ##

- **Payara Version**: 5.193
- **Edition**: Full
- **JDK Version**: 11 zulu
- **Operating System**: CentOS
- **Database**: doesn't matter

**Comment by rdebusscher** [comment]
Hi @peterpz1,

If your video download functionality runs in the same transaction as the execute() method, the failure of the transaction triggers a retry of the timer.
The number of retries is configurable (through webConsole for example)

Configurations > (config name) > EJB Container > EJB Timer Service (Tab) > Maximum Redeliveries (field)

The timeout of a Transaction can be configured by using the glassfish-ejb-jar.xml file

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sun-ejb-jar PUBLIC "-//Sun Microsystems, Inc.//DTD Application Server 9.0 EJB 3.0//EN" "http://www.sun.com/software/appserver/dtds/sun-ejb-jar_3_0-0.dtd">
<sun-ejb-jar>
    <enterprise-beans>
         <ejb>
            <ejb-name>YourEjbName</ejb-name>
            <cmt-timeout-in-seconds>1200</cmt-timeout-in-seconds>
         </ejb>
    </enterprise-beans>
</sun-ejb-jar>
```

Or though the @TransactionTimeout annotation.

If this download functionality doesn't require transactions, I suggest that you implement it in a CDI bean. Otherwise you will need to adjust the Transaction timeout.

The reason why it takes 13 minutes could be related to your code and I can't determine this based on the information you supplied.

Regards
Rudy
