### ISSUE TITLE
[QUESTION] Database galera cluster support

### ISSUE THREAD

**Issue by peterpz1** [payara/Payara#4290]
We have a situation in which we will have MariaDB Galera cluster deployed. This cluster doesn't have any single point of contact, you can contact any node in the cluster (every node is master node). We are wondering if Payara supports such datasources which will automatically talk to the random node and if this node fail it will switch to another one?

**Comment by rdebusscher** [comment]
Hi,

Payara supports any JDBC driver and since the MariaDB driver has support for the Galera cluster, it is possible to connect to the first available host as described on their documentation page:  https://mariadb.com/kb/en/library/about-mariadb-connector-j/#failover-and-load-balancing-modes

Regards
Rudy
