### ISSUE TITLE
Calling @Asyncronous remote EJB from MDB fails under heavy load

### ISSUE THREAD

**Issue by lprimak** [payara/Payara#432]
Regression from GF 4.1 final
This is an upstream bug: https://java.net/jira/browse/GLASSFISH-21379

**Comment by lprimak** [comment]
This was very hard to reproduce.  This happened when I tried to put the GF nightly in production and it happened about once a week.  I am not even sure when to begin to make a reproducible test case.

**Comment by lprimak** [comment]
I was hoping somebody could just look at the stack trace and can see something glaringly wrong with the GF code in question.

**Comment by realityforge** [comment]
We have found that any method annotated with `@Asyncronous` will fail under load regardless of the calling context and this has been observed this in all the GF 4.x releases. 

Rather than trying to address this we ended up using manual queueing (i.e. Database save + subsequent action via `@Schedule` annotated method) and added a checkstyle rule to disallow use of the annotation.

**Comment by lprimak** [comment]
Wow. This sounds serious. Has anyone raised this issue with the GF team or tried to resolve it?  With all the current focus on reactive this should get some more attention.

**Comment by smillidge** [comment]
@realityforge What errors do you see?

@lprimak The Test Case Required doesn't mean you have to give us one. Just we need one developing internally. If you have one then that would be great ;-)

**Comment by realityforge** [comment]
@smillidge Sorry - I don't have a copy of the errors and can't quite remember the details. We have worked around the problem for a while - just assumed that @Asynchronous was too experimental a feature to use

**Comment by smillidge** [comment]
Closing as @lprimak requested the corresponding GF bug to be closed
