### ISSUE TITLE
Testing with injected microprofile configuration

### ISSUE THREAD

**Issue by Mixermachine** [payara/Payara#4364]
# Description #
----------
My project uses the injection api of MicroProfile Configuration to get it's config variables.
Example:
```
@Inject
@ConfigProperty(name = PropertiesConfigSourceProvider.APP_MSID)
private String microserviceId;
```

## Expected Outcome
When I test my application I want to write a test with JUnit 5 and Mockito like
```
@ExtendWith(MockitoExtension.class)
public class MyTest {
    @Mock
    private Config config;

    @InjectMock
    private ClassUnderTest classUnderTest;
...
}
```
(Or some variation of that)

## Current Outcome

Currently this only works for configurations which are optained by

```
private Config config;

@Inject
public void setConfig(final Config config) {
    this.config = config;
}
```
and not for variables that are injected by
```
@Inject
@ConfigProperty(name = PropertiesConfigStatic.SVDS_HUB)
private String microserviceId;
```
The variable microserviceId is simply null.

## Steps to reproduce (Only for bug reports) 

Create a class with one property which is injected with ConfigProperty
Create a test class which test the previous class and tries to specify the value of the injected variable.

### Samples
MyClass.class
```
@Inject
@ConfigProperty(name = Statics.MY_VALUE)
private String myValue;
```

MyTest.class
```
@ExtendWith(MockitoExtension.class)
public class MyTest{
    @Mock
    private Config config;

    @InjectMock
    private MyClass myClass;

    @BeforeEvery
    public void setup() {
        Mockito.when(config.getValue(Statics.MY_VALUE, String.class)).thenReturn("A nice test variable");
    }
   ...
}
```

## Environment ##

- **Payara Version**: 5.192
- **Edition**: Micro
- **JDK Version**: Oracle 8
- **Operating System**: Windows
- **Database**: PostgreSQL 

Can you help me to inject the right variables into my classes?
Thanks in advance 👍 

Greetings from Munich

**Comment by rdebusscher** [comment]
Hi @Mixermachine 

The value for the `microserviceId` property is injected by the CDI container when the class/bean is instantiated.

During unit testing, there is no such container and thus the property doesn't get a value.  Also mocking and defining a value with `Mockito.when()` doesn't help since the Config class is not used (unless you retrieve the configuration value programmatically)

The easiest way is just setting the value through reflection. Maybe you have already a method for setting a variable through reflection, otherwise one can be created with a few lines of code.

Switching to the programmatic retrieval of your value in the `ClassUnderTest` just for the sake if testing, is not a good idea.

The other alternative is that you perform some integration testing where you have the CDI container available.

Regards
Rudy

**Comment by Mixermachine** [comment]
Hy @rdebusscher,

thanks for your answer.
As I understand it `@ExtendWith(MockitoExtension.class)` (JUnit5 and Mockito) provides the CDI environment for me.
Under JUnit4 with Mockito this would be `@RunWith(MockitoJUnitRunner.class)`.
All the entries which are marked with `@Mock` are automatically mocked and injected into the `@InjectMock` entry.

Using `Mockito.when()` with `Config` works in the `ClassUnderTest` if the `Config` object is directly used (Mockito injects the dependency for me).
Is there something similar for `ConfigProperty`?


Using reflection here is a good thought. Thanks.
Can I search for the defined name of the `ConfigProperty` via reflection or is this information hidden?
I would need to insert the values in all lower classes (`ClassUnderTest` accesses other classes which contain `@ConfigProperty` too).

It would be great if I could somehow tell the Mockito CDI to apply the ConfigProperties correctly.

Best regards

Aaron

**Comment by rdebusscher** [comment]
Hi,

I would not call JUnit5 and Mockito a CDI container. It does not check for the @Inject annotations. It uses reflection and matches types between @Mock test class properties and properties in the classUnderTest.

So when using @ConfigProperty in combination with Mockito, one should be able to use

>@Mock
String configValue;

which is not possible because String is a Final class.

You can check for @ConfigProperty during reflection as the annotation is present at runtime (otherwise MP Config would not be able to work)

**Comment by Mixermachine** [comment]
Hi @rdebusscher ,

you definitelly have more knowledge there than I do ^^.
Thanks for your description and pointing me in the right direction.
I now recursively search threw all fields and superClasses of a given object and collect all @ConfigProperty variables via Java Relfection.
Maybe I create a separate Maven project from it, if I have some free time on my hands.

Best regards

Aaron
