### ISSUE TITLE
[QUESTION] OpenApi and OpenApiUi set up

### ISSUE THREAD

**Issue by peterpz1** [payara/Payara#4470]
I'm struggling to understand how should OpenApi work. I have multiple applications on single payara domain, so:
1. From what I see there is one root endpoint which hosts openapi file (/openapi)? Can they be a individual files for each applications?
2. How to enable Swagger UI extension? I've did everything like here:
http://www.adam-bien.com/roller/abien/entry/installing_and_deploying_swagger_ui

And still no openapi-ui. I was looking in paths like:
http://server:port/openapi-ui
http://server:port/Application/openapi-ui
http://server:port/Application/restRootPath/openapi-ui

Everything results in 404 error. And readme states:
https://github.com/microprofile-extensions/openapi-ext/blob/master/swagger-ui/README.md

"Just adding the above will already give you the default UI, example:" - so it should automatically appear.

I will be grateful for help on setting this up.

EDIT:
I did some testing at first what I see is that root openapi file is showing only services from last deployed application. Is that true? There is really need for individual files then.

**Comment by svendiedrichsen** [comment]
Have you tried to post this question on the payara forum? https://groups.google.com/forum/#!forum/payara-forum

Maybe someone there already came across this problem.

**Comment by peterpz1** [comment]
I didn't know about this forum. Thank you, I've posted it there also. But I still think it would be good to explain here the behaviour of root openapi hosted file, because if there is >1 application I think it doesn't work properly - it cannot show services of last deployed application, it it useless...

**Comment by OndroMih** [comment]
Hi, @peterpz1,

If you think something doesn't work as expected, could you please create a sample reproducer project or at least clearly specify what you did and what doesn't work as you expect?

It's good that you asked the question on the forum, it's much better medium to raise questions and share experience within the Payara user community. For completness, here's the link to the question raised in the forum: https://groups.google.com/forum/#!topic/payara-forum/T00EvC8cMWg

**Comment by rdebusscher** [comment]
Hi @peterpz1 

It is correct that when you deploy multiple applications, only for one of them the openAPI document is generated.  This is because the MicroProfile specifications are designed for a single deployment, not multiple on the same instance. (As micro-services needs to be independent of each other and thus cannot share the same runtime)

If you want to have support for multiple applications, please open a request in the [MicroProfile repository](https://github.com/eclipse/microprofile/issues) for the Architecture board so that your request can be addressed.

Regarding the openAPI UI, I followed the description in the [readme](https://github.com/microprofile-extensions/openapi-ext/tree/master/openapi-ui) of the openapi extension project and everything worked as expected.

Regards
Rudy
