### ISSUE TITLE
./asadmin start-domain fails

### ISSUE THREAD

**Issue by YiannisKar** [payara/Payara#4472]
When i'm trying to run from Powershell payara with this command "./asadmin start-domain " i get the following errors:

Launching Payara Server on Felix platform

ERROR: Unable to create cache directory: C:\Program Files\payara5\glassfish\domains\domain1\osgi-cache\felix
ERROR: Error creating bundle cache
Caused by: java.lang.NullPointerException
        at com.sun.enterprise.glassfish.bootstrap.osgi.OSGiGlassFishRuntimeBuilder.newFramework(OSGiGlassFishRuntimeBuilder.java:241)

**Comment by peterpz1** [comment]
Are permissions on catalogues ok? More specifically if the user which is logged into PS is allowed to modify catalogs under C:\Program Files\payara5?

**Comment by fturizo** [comment]
Greetings @YiannisKar, considering the information you have shared I'd recommend you to inspect the permissions of both the user you are using to run the `asadmin` utility and the domain directory. Since this is not a proper bug report, but a contextual issue based on your environmental conditions,  I'll proceed to close this issue. 

Feel free to get additional assistance on the [Payara Forum](https://groups.google.com/forum/#!topic/payara-forum/) if you are still requiring additional assistance with setting correctly these permissions.
