### ISSUE TITLE
Replace Embedded Tomcat with upstream Catalina

### ISSUE THREAD

**Issue by smillidge** [payara/Payara#4557]
# Description #
----------
Payara Server and Payara Micro currently implement the Servlet and related specifications through an embedded version of Tomcat code which is quite old. This code will be replaced with upstream artefacts from the Tomcat project.

**Comment by smillidge** [comment]
First step is to review Grizzly servlet implementation and see how far it is from a full blown Servlet implementation that can p[ass the Jakarta EE 9 TCK.

**Comment by smillidge** [comment]
We have decided to replace custom Catalina code with upstream Catalina code.

**Comment by fturizo** [comment]
Dear users,
 
Due to process changes we have removed the undelivered roadmap items from this section and closed the related Project.
It is important to us that you continue to have visibility of our roadmap, so we will be sharing details regularly through other channels while we define the ideal way to share these details on GitHub.

Thank you for your understanding.
