### ISSUE TITLE
Reference Architecture for Payara Micro on Kubernetes

### ISSUE THREAD

**Issue by smillidge** [payara/Payara#4559]
# Description #
----------
As a user of Payara Micro I want to use Kubernetes either on premise or in the cloud as the operational deployment platform. What is the recommended Payara way of configuring and deploying Payara Micro applications into a Kubernetes infrastructure?

We have a large amount of capabilities for running clustered micro applications on kubernetes in general we need a reference architecture that brings the capabilities together in a document for users of Payara Micro and identifies improvements that can be added to the core runtime. 

Reference architecture to include

- Basic clustered configuration
- Monitoring and Healthchecks using MicroProfile capabilities
- Autoscaling

**Comment by fturizo** [comment]
Dear users,
 
Due to process changes we have removed the undelivered roadmap items from this section and closed the related Project.
It is important to us that you continue to have visibility of our roadmap, so we will be sharing details regularly through other channels while we define the ideal way to share these details on GitHub.

Thank you for your understanding.
