### ISSUE TITLE
Service Mesh Capabilities

### ISSUE THREAD

**Issue by smillidge** [payara/Payara#4560]
# Description #
----------
As an architect I would like to get Service Mesh capabilities for REST services and clients without the complexity of installing a dedicated cloud mesh infrastructure.

The service mesh would be configurable in the console and would enable REST clients to have these built in capabilities when invoking REST services.

Can provide URL round robin
Can provide endpoint failure detection and smart failover
Can provide fast failure
Can provide bulkhead
Can add additional security
Can create circuit breaker
Can provide timeout configuration
Retry policies
Rate limiting
Fault-injection
Rapid intra-grid calls i.e. not using HTTP
Rapid single server calls - when service on the same instance
Security and key management
Metrics – latency, failures, traffic, tracing integration, logging and auditing
Response Caching across the grid

**Comment by fturizo** [comment]
Dear users,
 
Due to process changes we have removed the undelivered roadmap items from this section and closed the related Project.
It is important to us that you continue to have visibility of our roadmap, so we will be sharing details regularly through other channels while we define the ideal way to share these details on GitHub.

Thank you for your understanding.
