### ISSUE TITLE
Reference Architecture and improvements for Payara Platform and ELK/Grafana/Prometheus stack

### ISSUE THREAD

**Issue by smillidge** [payara/Payara#4562]
# Description #
----------
Users have expressed a desire to monitor Payara using the above stacks. We have a number of capabilities through MP Metrics/JMX logger/Healtchecks/REST interface etc. We need to provide the one Payara way and include new additional product capabilites that make it way easier and logical.

**Comment by fturizo** [comment]
Dear users,
 
Due to process changes we have removed the undelivered roadmap items from this section and closed the related Project.
It is important to us that you continue to have visibility of our roadmap, so we will be sharing details regularly through other channels while we define the ideal way to share these details on GitHub.

Thank you for your understanding.
