### ISSUE TITLE
Autotuning request processing

### ISSUE THREAD

**Issue by smillidge** [payara/Payara#4563]
# Description #
----------
One of the most popular features indicated in the community survey was autotuning thread pools within Payara. Auto-tuning would provide automatic tuning of http request processing using specified policies.

**Comment by fturizo** [comment]
Dear users,
 
Due to process changes we have removed the undelivered roadmap items from this section and closed the related Project.
It is important to us that you continue to have visibility of our roadmap, so we will be sharing details regularly through other channels while we define the ideal way to share these details on GitHub.

Thank you for your understanding.
