### ISSUE TITLE
JPA: entityType.getId(entityType.getIdType().getJavaType()) fails on primitives

### ISSUE THREAD

**Issue by fcorneli** [payara/Payara#4651]
I have an entity with:
```
@Id
@GeneratedValue(strategy = GenerationType.AUTO)
private long id;
```
Doing:
```
Metamodel metamodel = entityManager.getMetamodel();
EntityType<?> entityType = metamodel.entity(MyEntity.class);
SingularAttribute idAttribute = entityType.getId(entityType.getIdType().getJavaType());
```
fails with:
```
Expected id attribute type [class java.lang.Long] on the existing id
attribute[SingularAttributeImpl[BasicTypeImpl@263824154:long [ javaType: long]
```
The `getId` method should be able to accept the primitive type.

Payara version: 5.201

**Comment by fcorneli** [comment]
In a way this makes sense, as the identifier can be null, and hence should actually be Long instead of long.

**Comment by fturizo** [comment]
Greetings @fcorneli. Apologies for taking this long to reply since I was consulting with our engineering team on the state of this issue. The consensus is clear: This is a design flaw of the JPA specification since the MetaModel's API `EntityType.getId` method signature does not allow the handling of primitives:

    <Y> SingularAttribute<? super X,Y> getId(Class<Y> type)

In which case the best solution is to switch to the `Long` wrapper class instead. I'll proceed to close this issue since this is not a proper bug at the moment.
