### ISSUE TITLE
Multiple errors like -> Class [ Lcommonj/work/WorkManager; ] not found. Error while loading [ class oracle.adfinternal.view.faces.activedata.AdsServlet ]]]

### ISSUE THREAD

**Issue by informaticajovani** [payara/Payara#4720]
Hi,

I am making a migration from Payara 4 to 5, whit thats config

- **Payara Version**:  5.201
- **JDK Version**: 8 Oracle
- **Operating System**: Linux CentOS 7

And I have too many errors. Previously I was already working with jdk 8.

Payara 5.201] [GRAVE] [] [Annotation-Framework] [tid: _ThreadID=210 _ThreadName=admin-thread-pool::admin-listener(5)] [timeMillis: 1    592221221002] [levelValue: 1000] [[
  Class [ Lcommonj/work/WorkManager; ] not found. Error while loading [ class oracle.adfinternal.view.faces.activedata.AdsServlet ]]]

[Payara 5.201] [GRAVE] [] [Annotation-Framework] [tid: _ThreadID=210 _ThreadName=admin-thread-pool::admin-listener(5)] [timeMillis: 1    592221221329] [levelValue: 1000] [[
  Class [ org/eclipse/jetty/server/Connector ] not found. Error while loading [ class org.apache.cxf.transport.http_jetty.JettyHTTPServerEngine ]]]

[Payara 5.201] [GRAVE] [] [] [tid: _ThreadID=210 _ThreadName=admin-thread-pool::admin-listener(5)] [timeMillis: 1592221221711] [level    Value: 1000] [[
  SLF4J: Class path contains multiple SLF4J bindings.]]

[Payara 5.201] [GRAVE] [] [] [tid: _ThreadID=210 _ThreadName=admin-thread-pool::admin-listener(5)] [timeMillis: 1592221221712] [level    Value: 1000] [[
  SLF4J: Found binding in [jar:file:/opt/payara/domains/mydomain/applications/mydomain/mydomain_war/WEB-INF/lib/slf4j-simple-1.7.2.jar!/org/slf4j/impl/StaticLogg    erBinder.class]]]

 [Payara 5.201] [GRAVE] [] [] [tid: _ThreadID=210 _ThreadName=admin-thread-pool::admin-listener(5)] [timeMillis: 1592221221712] [level    Value: 1000] [[
  SLF4J: Found binding in [jar:file:/opt/payara/domains/mydomain/lib/slf4j-simple-1.7.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]]]

[Payara 5.201] [GRAVE] [] [] [tid: _ThreadID=210 _ThreadName=admin-thread-pool::admin-listener(5)] [timeMillis: 1592221221712] [level    Value: 1000] [[
  SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.]] 

I hope you can give me light

**Comment by rdebusscher** [comment]
Hi,

The first 2 messages are about dependencies. If these dependencies are bundled in your web application, you probably need to change the classloading. See for more information here https://docs.payara.fish/community/docs/5.2020.2/documentation/payara-server/classloading.html.

Since you are adding Apache CXF, this change in classloading is always advisable so that there is no conflict with the implementation Payara has already included (like Metro for JAX-WS)

The last messages are about the inclusion of slf4j-simple into your WAR file but it is already included in the Payara Server and thus SLF4J API warns you about this duplication.

Regards
Rudy

**Comment by MeroRai** [comment]
Hi @informaticajovani,

Due to the lack of activity form you, I am closing this issue immediately. If the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Server Community edition and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.
