### ISSUE TITLE
Too long certificate_authorities extension in TLS ClientHello

### ISSUE THREAD

**Issue by robelcik** [payara/Payara#4751]
# Description #
----------

Recently, probably due to the new features in JDK 8.251(2), Payara started to add _certificate_authorities_ to _ClientHello_ message. Since `cacerts.jks` contains quite a few entries, the list is a long one. 

In my application, I'm calling a REST service which has SSL set up on AWS ELB level. Apparently, that server does not like the "new" _ClientHello_ messages. Returned data causes SSL exceptions on Payara side. After I limited `cacerts.jks` to one entry everything worked fine. Also everything worked fine after downgrading Java to 242.

I'm not sure that the length is the cause there. https://bugs.openjdk.java.net/browse/JDK-8206925 says something about splitting messages above 16k and that's why it was my first thought. Of course, it could be something else inside _certificate_authorities_ (non-ascii characters???)

I  produced logs by using `-Djavax.net.debug=ssl:handshake:verbose`. The only difference between Java .242 and .252 was presence of _certificate_authorities_.

## Expected Outcome

TLS handshake produced by Payara is accepted by AWS ELB.

## Current Outcome

Server seems not to accept _ClientHello_ message and replies with data which causes exception in Payara

Exceptions like:
```
javax.ws.rs.ProcessingException: javax.net.ssl.SSLHandshakeException: Received fatal alert: illegal_parameter
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:261)

TransportContext.java:344|Fatal (UNEXPECTED_MESSAGE): Software caused connection abort: recv failed (
"throwable" : {
  java.net.SocketException: Software caused connection abort: recv failed
  	at java.net.SocketInputStream.socketRead0(Native Method)
```

## Steps to reproduce (Only for bug reports) 

Example code below. I'm a bit afraid of publishing exact URL here.

```
Response response = ClientBuilder.newBuilder()
        .register(JacksonFeature.class)
        .build()
        .target("https://example.url")
        .request(MediaType.APPLICATION_JSON_TYPE)
        .post(Entity.json(request));
```

## Environment ##

- **Payara Version**: 5.2020.2 Community Edition
- **Edition**: Full
- **JDK Version**: zulu8.46.0.19-ca-jdk8.0.252-win_x64
- **Operating System**: Windows
- **Database**: N/A

**Comment by smillidge** [comment]
This looks more like a JDK bug than a Payara bug especially as downgrading the JVM fixes it.

**Comment by robelcik** [comment]
Hello. Thank you for your reply.

It looks like the cause is OpenJSSE included in Zulu JDK. After disabling it, by removing `-XX:+UseOpenJSSE` in `domain.xml`, "Sun's" implementation was used which did not cause problems.

Do you know it removal of `-XX:+UseOpenJSSE` has other consequences apart from removing support for TLSv.1.3?

**Comment by smillidge** [comment]
@rdebusscher can we raise a Zulu issue for this?

**Comment by rdebusscher** [comment]
This needs more investigation since Zulu 8.48 (8u262) now has TLS 1.3 support by default.

I'll create tests with 8.46 and 8.48 to confirm the issue as it might also be an issue with incompatibility between implementations (as hinted here https://bugs.openjdk.java.net/browse/JDK-8206925?focusedCommentId=14338530&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14338530)

**Comment by rdebusscher** [comment]
Hi,

I have tested Zulu 8.48 (based on openJDK 8u262) and the _certificate_authorities_ extension is not send in the `ClientHello` message with this version.  So it is advised to upgrade to this Zulu JDK release.

Also, due to the removal of some expired certificates in release 5.2020.3, the message is now also just below the 16k boundary length for the 182 certificates in the truststore.

`javax.net.ssl|DEBUG|01|main|2020-07-28 11:11:34.093 CEST|SSLSocketOutputRecord.java:175|WRITE: TLS13 handshake, length = 16367`

Regards
Rudy

**Comment by rdebusscher** [comment]
And to answer your other question, the option `-XX:+UseOpenJSSE` has only an effect on the TLS v1.3 support.
