### ISSUE TITLE
Applications in DEPLOY_DIR aren't deployed if a custom read-only POSTBOOT_COMMAND file is provided // FISH-371

### ISSUE THREAD

**Issue by viktorcitaku** [payara/Payara#4825]
# Description #
----------

Based on the Docker Hub documentation of the [Payara Server](https://hub.docker.com/r/payara/server-full), there is an environment variable defined named DEPLOY_DIR which says: `The directory where applications are searched for in generate_deploy_commands.sh script.`. However, it doesn't work as it's expected.

The example that I am running is located [here](https://github.com/viktorcitaku/modular-jee).

## Expected Outcome

I expect my WAR application to be deployed.

## Current Outcome

The application is not deployed.

## Steps to reproduce (Only for bug reports) 

1. `git clone git@github.com:viktorcitaku/modular-jee.git`
2. `mvn clean install`
3. `docker-compose up --build`

## Context (Optional)

I did a workaround where I deploy my WAR via the `post-boot-commands.asadmin` script.

The potential issue might be related to the following log entries, which appear at the beginning when the Payara Server container starts.
```
[Entrypoint] running /opt/payara/scripts/init_1_generate_deploy_commands.sh
touch: cannot touch '/opt/payara/config/post-boot-commands.asadmin': Permission denied
post boot commands already deploys /opt/payara/deployments/web-module-1.0.0-SNAPSHOT.war

[Entrypoint] ignoring /opt/payara/scripts/init.d/*

touch: cannot touch '/opt/payara/config/post-boot-commands.asadmin': Permission denied
```

## Environment ##

- **Payara Version**: 5.2020.3
- **Edition**: Full
- **JDK Version**: zulu-8-amd64 (from official Payara Docker image (latest))
- **Operating System**: from official Payara Docker image (latest)
- **Database**: Not relevant

**Comment by OndroMih** [comment]
Hi @viktorcitaku,

I've tested your reproducer and I see what you see. However, the Docker container doesn't ignore the `$DEPLOY_DIR` variable. The problem is that you overwrite the `$POSTBOOT_COMMANDS` file and this file is created under the `root` user. The default `payara` user can't modify it in order to add deploy commands for applications in the `$DEPLOY_DIR` directory.

To fix this, you only need modify the `COPY` command to create the file under the `payara` user. This works in Docker 17.09+ :

```
COPY --chown=payara ./scripts/post-boot-commands.asadmin ${POSTBOOT_COMMANDS}
```

If you use an older Docker version, you need to run the following:

```
COPY ./scripts/post-boot-commands.asadmin ${POSTBOOT_COMMANDS}
USER root
RUN chown payara:payara ${POSTBOOT_COMMANDS}
USER payara
```
You also need to add a new line at the end of your `./scripts/post-boot-commands.asadmin`. The boot scripts in the container add deploy commands right at the end of the file and if the file doesn't end with a new line the commands get mingled in the same line.

It's worth to enhance the boot scripts to expect that the POSTBOOT_COMMANDS file isn't writable and also that it doesn't end with a new line.

**Comment by viktorcitaku** [comment]
Hi @OndroMih ,

Thank you, your solution worked.
