### ISSUE TITLE
asadmin generate-bash-autocomplete incomplete

### ISSUE THREAD

**Issue by g0rill4z** [payara/Payara#4878]
# Description #
----------

`asadmin generate-bash-autocomplete` does not include all available commands (eg. `start-domain` or `start-domains`).
In general the completion is not as helpful as it might be since it does not offer completion for the specific commands.

## Expected Outcome

Expected having a fully-featured completion.

## Current Outcome

Completion does not offer a variety of commands and does not feature any completion for specific commands.

## Steps to reproduce (Only for bug reports) 

- Run `asadmin start-domain`
- Run `asadmin generate-bash-autocomplete`
- Copy the resulting file to `/usr/local/etc/bash-completion.d/`
- Restart your bash terminal.

## Environment ##

- **Payara Version**: 5.2020.4
- **Edition**: Community
- **JDK Version**: 8 Oracle
- **Operating System**: macOS 10.14.6

**Comment by khasunuma** [comment]
I'd like you to give us more detail. So, please let us know what you hope we would do and what you could contribute for this issue in particular.

The `asadmin` utility has two kind of sub-commands - the "local" commands and the "remote" commands. Regarding to the difference, see https://stackoverflow.com/questions/15159113/difference-between-glassfish-server-local-and-remote-commands

Then, `asadmin generate-bash-autocomplete` generates a bash script to suggest "remote commands" in design. Because most of commands to manage Payara Server are the "remote" commands. On the other hand, the "local" commands are provided for limited operations, e.g. start and stop domain / local instance.

**Comment by MeroRai** [comment]
Hi @g0rill4z,

Due to the lack of activity form you, I am closing this issue immediately. If the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Server Community edition and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.
