### ISSUE TITLE
Payara Micro sends all output to Error-Stream

### ISSUE THREAD

**Issue by Herr-Sepp** [payara/Payara#4907]
# Description #
----------

All output from Payara Micro Dockercontainer are send to Error-Stream (stderr).
You can`t read the containerlogs on systems with "Stop-On-Errors"-mode.

## Expected Outcome

Only errors should be inside the error-stream, all other logging belongs to stdout.

## Steps to reproduce (Only for bug reports) 

docker run --rm --name payara payara/micro

docker logs payara 1> stdout.log
docker logs payara 2> stderr.log

stdout.log is empty and stderr.log has all logging in it even if there are no errors.

**Comment by dmatej** [comment]
This is because Payara Micro uses standard JDK's ConsoleHandler which always uses STDERR as the output. Good explanation for that is here: https://stackoverflow.com/a/34159008/375449 . I agree it is not much nice, but you can always provide your own implementation.

See also: https://docs.payara.fish/community/docs/5.2020.4/documentation/payara-micro/adding-jars.html

**Comment by Herr-Sepp** [comment]
@dmatej Thanks for your explanation.
Maybe a hint on the docker-hub page would be good that all output is done on stderr.
