### ISSUE TITLE
When defined whitelist-package, the provider-configuration file in META-INF/services contained in the application was not loaded.

### ISSUE THREAD

**Issue by otukatigayim** [payara/Payara#4985]
# Description #
----------

When defined whitelist-package, the provider-configuration file in META-INF/services contained in the application was not loaded.
* https://docs.payara.fish/community/docs/5.2020.5/documentation/payara-server/classloading.html#extreme-classloading-isolation

## Expected Outcome

The application's provider-configuration file is loaded.

## Current Outcome

When defined whitelist-package, the provider-configuration file in META-INF/services contained in the application was not loaded.

## Steps to reproduce (Only for bug reports) 

1. Build the following Appilication. ``mvn clean package``
    - https://github.com/otukatigayim/payara-whitelist
2. Deploy application. ``asadmin deploy --name=payara-whitelist --virtualservers=server payara-whitelist.war``
    - MyServiceImpl could not be loaded in MyServletContextListener and a RuntimeException was thrown.
    - https://github.com/otukatigayim/payara-whitelist/blob/master/src/main/java/com/otukatigayim/payara_whitelist/MyServletContextListener.java#L22

No Exception was thrown when defined the application's provider configuration file in whitelist-package.
- https://github.com/otukatigayim/payara-whitelist/blob/master/src/main/webapp/WEB-INF/glassfish-web.xml#L6

### Samples

- https://github.com/otukatigayim/payara-whitelist/

## Environment ##

- **Payara Version**: 5.2020.5
- **Edition**: Full
- **JDK Version**: 8
- **Operating System**: Windows
- **Database**: None

**Comment by AlanRoth** [comment]
Hi otukatigayim, 

Upon some investigating, this is expected behavior. Extreme classloading applies to both classes and their resources, when extreme classloading is enabled (by defining a whitelist-package) you provide the classes and resources you would like Payara to load. The correct use is to list your service as you have done in the commented out line, or a partial path (i.e META-INF/service/com.otukatigayim) if you expect to include more services, as this will load all services sharing that path. If you would like to load any service just whitelist 'META-INF/service'.

Hope this clarifies things.

Thank you,
Alan

**Comment by otukatigayim** [comment]
Hi Alan,

Thank you for investigating.

I was thinking that if the whitelist was defined, the behavior would be as follows.
* The classes and resources contained in Payara Server are loaded only if they are defined in the whitelist.
* The classes and resources contained in the deployed application would be loaded unconditionally.

Thank you,
otukatigayim
