### ISSUE TITLE
[payara-api - openid connect] Not compatible to Active Directory Federation Service

### ISSUE THREAD

**Issue by markusg80** [payara/Payara#5083]
# Description #
----------
The openid implementation of the payara security library cannot handle adfs. this is because adfs needs extra parameter to get all claims.

## Expected Outcome

The openid request to adfs returns all claims requested by scopes and extra claims from the web api definition in adfs.

## Current Outcome

adfs returns 401 error because it expect an extra parameter named **resource**. After i set the paramter resource in the definitions extra parameter to **resource=urn:microsoft:userinfo** it returns the claim sub from userinfo endpoint and inside the Identity Token there are some basic user info like upn. but it respects only the scope **openid** all other scopes are not respected.

### Prepare adfs
Install adfs and create server application group with webapi. Make sure the webapi has same id like server application. In the webapi prpoerties add some claims in the issuance transform rules.

### In the example project set this parameter

Set **redirectURI,clientSecret,clientId,providerURI** properties to fit your adfs installation. then set scope **openid allatclaims** and responseType to **code**.

## Context (Optional)

I tryed to set the resource parameter to the webapi identifier for example **c45d1e0b-0f18-4a92-ab3c-a32b12075a8b** or **https://web1.test.local/TestItsNg** but hen always i see with wireshark in the /userinfo endpoint request the http return error coe 401 with message 

> Bearer error="invalid_token", error_description="MSIS9921: Received invalid UserInfo request. Audience 'microsoft:identityserver:c45d1e0b-0f18-4a92-ab3c-a32b12075a8b' in the access token is not same as the identifier of the UserInfo relying party trust 'urn:microsoft:userinfo'."

When i set extra parameter to urn:microsoft:userinfo the i got back the sub claim from userinfo endpoint and inside identity token there are some basic info about user.

After a while i find out that the adfs reource parameter has also o be dded to the token endpoint request there is no resource parameter added.
>HTML Form URL Encoded: application/x-www-form-urlencoded
>   Form item: "client_id" = "c45d1e0b-0f18-4a92-ab3c-a32b12075a8b"
>    Form item: "client_secret" = "yhHfNywTBU9gnCp8dEHfgdFwin1x5XStQJEvCpdG"
>    Form item: "grant_type" = "authorization_code"
>    Form item: "code" = "mDq0_AH7B0Sjtyg89YuIkg.aWyGs-uv2AgFABog0Mik6rhtB7o.KKe5DS1mkj9g-Cc5IT445nISrLzk4H0U5q6bmE4STM2eMncsxMMmXY1IaUz80DSmhrEN_jk7XUIWgP83ryjBjN3IZTTzSlpdSWLBuMndMxMTjviI_QY0SQ3QeFpahCWWocN9rwU3O3BtG7L8G2kIovxuHlabYREO9w6RiYH
>    Form item: "redirect_uri" = "https://web1.test.local:8181/TestItsNg/callback"

So this means that you should either add the extra parameters also to the token request, implement new exra parameter only for token request or make it possible to deactivate the userinfo endpoint call.

## Environment ##

- **Payara Version**: 5.2020.7
- **Edition**: Full
- **JDK Version**: Tested with 8 and 11
- **Operating System**: Windows
- **Database**: not needed

**Comment by AlanRoth** [comment]
Hi @markusg80, are you able to provide a simpler reproducer? The steps provided are too ambiguous to reliably reproduce, it should ideally follow the SSCCE rules: http://www.sscce.org/. 

If you are able, you may also submit a PR to implement this feature yourself, and we will be more than happy to review it, thank you.

**Comment by markusg80** [comment]
Maybe i make a pull request for this but i saw that the relying code is in the ecosystem-security-connectors repo. So the question is if i have to move this issue to that repo?

another hint:
I believe that this is already possible with openliberty. They have resource paramter for openid connect client.

https://openliberty.io/docs/20.0.0.12/reference/config/openidConnectClient.html

see resource attribute.

**Comment by AlanRoth** [comment]
Hi @markusg80, 

The issue is ok here. If you are able to submit a PR that would be great and we'd be more than happy to review it! Just make sure to link it to this issue if you do make a PR to ecosystem-security-connectors. I also believe you will have to sign a CLA before we accept your PR, if you have not already sent one.

Thank you,
Alan

**Comment by markusg80** [comment]
You have to help me a little bit, because i contribute first tme for a project in Github. So why are not all classes from ecosystem-security-connectors repo inside this brach? They are need for authentication bringing to work. So how can i create a PR and link this to this issue?

**Comment by AlanRoth** [comment]
Hi @markusg80, 

The server does not depend on ecosystem-security-connectors so they can be separated from the main repo.

You can make a PR against the ecosystem-security-connectors repo, just mention this issue in your PR and it should make a link :) At the very least it will let me know that this issue is related to the PR - and I can keep track of everything so don't worry.

Thank you,
Alan

**Comment by markusg80** [comment]
I'm so sorry but i don't know the exact internals of the payara server. I was able to change the related part, at least i think so ;-). So i try to test my change but i was not able to implement the resulting jar files from ecosystem-security-connectors build to payara modules. There it is special a special version of those modules not directly from the ecosystem-security-connectors repo. So how can i test my changes with a payara server? i have to build the hole payara server project?

**Comment by jGauravGupta** [comment]
Hi @markusg80, 

Currently, we are maintaining both the ecosystem-security-connectors and Payara internal modules. But due to some OSGI related issues, ecosystem-security-connectors artifacts can't be placed in Payara modules. Soon we will remove the internal modules of security connectors from the Payara repo by fixing the OSGI issue.

So as of now, You may apply your changes to the internal [OpenID Connect](https://github.com/payara/Payara/tree/master/appserver/payara-appserver-modules/security-openid) module and build the Payara Server by [following this instruction](https://docs.payara.fish/community/docs/5.2020.7/build-instructions/build-instructions.html).

**Comment by markusg80** [comment]
So i have done and tested the modifications. But it seeams that i doesn't have permission to create a branch

**Comment by jGauravGupta** [comment]
Hi @markusg80 ,

Please create the branch in your fork, You may follow more details here: https://blog.payara.fish/how-to-contribute-to-payara-server

**Comment by AlanRoth** [comment]
Hi Markus, 

As your PR to implement this feature did not meet our standards, and our engineering team does not have the bandwidth to commit resources to implement this feature, I will be closing this issue.

I apologize for any inconvenience caused and I thank you for your understanding,
Alan
