### ISSUE TITLE
Bug Report:  Remote Lookup of administered objects no possible in payara 4.x

### ISSUE THREAD

**Issue by alexwala** [payara/Payara#5147]
# Description #
----------

Remote Lookup of administered objects using configured properties no possible in payara 4.x
see PAYARA-3815 (#4006)

## Expected Outcome ##

Support Remote Lookup of administered objects (in AdministeredObjectFactory)

## Current Outcome ##

Configured properties are not preserved when looking up administered objects

## Steps to reproduce ## 

lookup remote destination using configured properties

```java
Properties env = new Properties();

env.setProperty(Context.INITIAL_CONTEXT_FACTORY, "com.sun.enterprise.naming.SerialInitContextFactory");
env.setProperty(Context.URL_PKG_PREFIXES, "com.sun.enterprise.naming");
env.setProperty(Context.STATE_FACTORIES, "com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl");
env.setProperty("org.omg.CORBA.ORBInitialHost", "my-host");
env.setProperty("org.omg.CORBA.ORBInitialPort", "3700");

InitialContext ctx = new InitialContext(env);
Destination destination = (Destination) ctx.lookup("jms/my-topic");
```

Workaround:
```
System.setProperty("org.omg.CORBA.ORBInitialHost", "my-host");
```

## Environment ##

- **Distribution**: Payara Server 4.1.2.174
- **JDK Version**: Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
- **Operating System**: Linux

**Comment by MeroRai** [comment]
Hi @alexwala, Payara Platform 4 has entered into the "Maintenance" lifecycle in February 2019. This means the quarterly updated has stopped and it is no longer available to our community users.

Although the Payara Platform 4 has gone into Maintenance, Payara Enterprise Customers of the Payara Platform will continue to receive support for legacy applications, OpenJDK support, backported fixes and platform certifications along with monthly security updates as well as access to our support services. If you are interested in Payara Enterprise, please contact Payara Sales at sales@payara.fish. You can also learn more about Payara enterprise here: https://www.payara.fish/enterprise/.

You can still raise the issue in our latest release of Payara Community Edition if the issue is present in it.
