### ISSUE TITLE
Bug Report:  Create new JMS connection from remote client not possible using configured properties in payara 4.x

### ISSUE THREAD

**Issue by alexwala** [payara/Payara#5149]
# Description #
----------

Create new JMS connection from remote client not possible in payara 4.x using configured properties

## Expected Outcome ##

Create new JMS connection from remote client using configured properties

## Current Outcome ##

ConnectionFactory.createConnection always tries localhost for create a new connection, regardless configured properties

## Steps to reproduce ## 

```java
Properties env = new Properties();

env.setProperty(Context.INITIAL_CONTEXT_FACTORY, "com.sun.enterprise.naming.SerialInitContextFactory");
env.setProperty(Context.URL_PKG_PREFIXES, "com.sun.enterprise.naming");
env.setProperty(Context.STATE_FACTORIES, "com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl");
env.setProperty("org.omg.CORBA.ORBInitialHost", "my-host");
env.setProperty("org.omg.CORBA.ORBInitialPort", "3700");

InitialContext ctx = new InitialContext(env);
ConnectionFactory connectionFactory = (ConnectionFactory) ctx.lookup("jms/my-connection-factory");
connectionFactory.createConnection();
```

Output is:
```
WARNING: [C4003]: Error occurred on connection creation [localhost:7676]. - cause: java.net.ConnectException: Connection refused: connect
```

Workaround:
```
System.setProperty("org.omg.CORBA.ORBInitialHost", "my-host");
```

## Environment ##

- **Distribution**: Payara Server 4.1.2.174
- **JDK Version**: Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
- **Operating System**: Linux

**Comment by MeroRai** [comment]
Hi @alexwala, Payara Platform 4 has entered into the "Maintenance" lifecycle in February 2019. This means the quarterly updated has stopped and it is no longer available to our community users.

Although the Payara Platform 4 has gone into Maintenance, Payara Enterprise Customers of the Payara Platform will continue to receive support for legacy applications, OpenJDK support, backported fixes and platform certifications along with monthly security updates as well as access to our support services. If you are interested in Payara Enterprise, please contact Payara Sales at sales@payara.fish. You can also learn more about Payara enterprise here: https://www.payara.fish/enterprise/.

You can still raise the issue in our latest release of Payara Community Edition if the issue is present in it.
