### ISSUE TITLE
Enhancement: Upgrade Jackson dependency

### ISSUE THREAD

**Issue by rradina** [payara/Payara#5330]
# Description #
----------

Current jackson-databind version 2.10.2 is associated with CVE-2020-25649

https://nvd.nist.gov/vuln/detail/CVE-2020-25649

## Expected Outcome

Upgrade jackson-databind dependency to version 10.2.5.1 or beyond

## Current Outcome

Dated jackson-databind dependency causes vulnerability scanners to declare Payara microbundle jar vulnerable XML injection attacks.  Vulnerability is 7.5 HIGH

## Alternatives

None

## Context

None

**Comment by shub8968** [comment]
Hi @rradina,

Thank you for raising the enhancement request, as you know, it will be submitted to voting by the community and accepted if it is the most voted issue this month. Also, If you can make the request more detailed. 

Thank you,
Shubham

**Comment by shub8968** [comment]
Thanks, @rradina.

For reporting the CVE of the mentioned dependency. I have created an internal JIRA and informed the platform development team about the same. We'd upgrade it in our future releases.

Also, Please address the security-related issues on security@payara.fish instead of using Payara-Platform's repositories or public forums. https://docs.payara.fish/community/docs/security/security.html#reporting-security-issues
