### ISSUE TITLE
The link to the release notes in `README.txt` is still incorrect. 

### ISSUE THREAD

**Issue by ahamana** [payara/Payara#5364]
On [5.2021.5](https://repo1.maven.org/maven2/fish/payara/distributions/payara-ml/5.2021.5/payara-ml-5.2021.5.zip), `README.txt` has two links to the release notes, one is correct, but another is still incorrect.
This issue is related to #5287.

> Make sure to also check the Payara Server 5.2021.5 Release Notes as they contain important information: docs.payara.fish/docs/5.2021.5/release-notes/release-notes-2020-7.html

> Payara Server 5.2021.5 Release Notes: docs.payara.fish/docs/5.2021.5/release-notes/release-notes-2021-5.html

Thanks,

**Comment by shub8968** [comment]
Hi @ahamana,

Thanks for keeping eye on it.  The link formatting was again missed due to the automated versioning scripts. The CI team is updating the scripts appropriately to ensure this doesn't happen in future versions. 

This will be fixed before the next release.

I will close this issue as we have all the information required.

Apologies for the inconvenience,
Thank you,
Shubham
