### ISSUE TITLE
Bug Report:   Invalid ejb jar 

### ISSUE THREAD

**Issue by kronos72it** [payara/Payara#5465]
# Description #
----------
I want to switch from Glassfish to Payara .Then tryed to deploy the developing EAR ,from Netbeans ,using Payara .
The same EAR that work fine running 'debug' toward GF (debug from NB) ,doesn't work if I try to run debug toward Payara .
I got this error during deployment :  Exception while deploying the app [HB-ear-1.0-SNAPSHOT] : Invalid ejb jar [HB-ejb-1.0-SNAPSHOT.jar]: it contains zero ejb.

I got this error during deployment :  
Exception while deploying the app [HB-ear-1.0-SNAPSHOT] : Invalid ejb jar [HB-ejb-1.0-SNAPSHOT.jar]: it contains zero ejb.
## Expected Outcome ##
I expect to complete deploy and see JSF pages because , I suppose, this is a bug of Payara , since the EAR work fine in GF .

NB 12.0 , GF 6 , Payara 5.2021.8 
The EAR is composed by Common jar, War, EJB .
Of course EJb module doesn't have an ejb-jar descriptor because I want to use Ejb Annotation .Anyway EJB module have some Stateless , Singleton and entities are packaged in Common jar .
## Current Outcome ##
 Exception while deploying the app [HB-ear-1.0-SNAPSHOT] : Invalid ejb jar [HB-ejb-1.0-SNAPSHOT.jar]: it contains zero ejb.

## Environment ##

- **Distribution**:  Payara 5.2021.8
- **JDK Version**:  JDK 11
- **Operating System**:  Win 7

**Comment by crprince** [comment]
I have had similar errors on occasion over the years with most application servers.  In my cases typically the EJB , EAR, WAR is actually invalid, but the cause is non-obvious.  

Usually the cause was that the build was running, but the compiled class files where not ending up in the ejb-jar, or it was not copied to the autodeploy folder completely.  Windows file locking issues being the most common cause, error in build.xml or pom.xml being the next most common for me.

There are a couple of things that you could you check for more information:

- use the NB file tab to inspect the build directory and expand into the jar files themselves, did everything actually get packaged.
- deploy the built ejb-jar manually in the admin console (or asadmin) with or without debug mode enabled.  (try with the verify option as well)

that will narrow things down.

**Comment by shub8968** [comment]
Hi @kronos72it 

Would you be able to provide the proper reproducer app in order to investigate it as per our contributing guidelines? If you think you need advice or guidance you can post a message on our community discussion platform.
https://forum.payara.fish/
