### ISSUE TITLE
Enhancement: Http 3 QUIC UDP Support

### ISSUE THREAD

**Issue by eix128** [payara/Payara#5495]
As we all know now http 3 is released and most browsers supporting http 3 now.
Its based on udp and its much faster then old tcp http
Some servers already support QUIC.

Currently on Java World , there is only one framework that supports quic ,
netty project.
You can checkout : https://github.com/netty/netty-incubator-codec-quic
And : https://github.com/netty/netty-incubator-codec-http3

**Comment by fturizo** [comment]
@eix128, usually as per our community support process, these types of requests would be passed over to our product management team so they can decide if they fit in the product's future roadmap and are aligned with the core standards that the Payara Platform adheres to. In this case, it is too soon to consider integrating HTTP3 and QUIC support in Payara Server due to a lot of issues (protocols not stable enough, lack of current vision for Servlet support on HTTP beyond v2, etc.), so I'm afraid that we'll proceed to close it. 

Feel free to revisit this issue in the future once HTTPv3 is fully released in the wild and gains RFC status.

**Comment by mkarg** [comment]
More than a year is over. Any news on HTTP/3?

**Comment by mkarg** [comment]
HTTP/3 is an official IETF standard since June 2022, see https://www.rfc-editor.org/rfc/rfc9114.txt.

**Comment by phillipross** [comment]
for some roadmap calibration... only now (2023-02-08) is NGINX making preview impls available of their offering: 
https://www.nginx.com/blog/binary-packages-for-preview-nginx-quic-http3-implementation/

**Comment by mkarg** [comment]
> for some roadmap calibration... only now (2023-02-08) is NGINX making preview impls available of their offering: https://www.nginx.com/blog/binary-packages-for-preview-nginx-quic-http3-implementation/

So it is the right time to put it on the roadmap for Payara. :-)

**Comment by mkarg** [comment]
Kindly requesting the reopening of this issue, so work on this will *start*, hence could be finished within this year. :-)

BTW, Traefik reverse proxy released 3.0.0-beta2 on December 7, including *non-experimental* support for HTTP/3, after having HTTP/3 *experimental* support since 2.x.
