### ISSUE TITLE
Payara 6 Community 

### ISSUE THREAD

**Issue by rdebusscher** [payara/Payara#5519]
Payara 6 will include

- Can be run on JDK 11 and 17
- Jakarta EE 10 certified  (jakarta namespace based)
- Passes the MicroProfile 5.0 Umbrella TCK speciifcations.
- Replaced old embedded Tomcat code.

**Comment by fturizo** [comment]
Dear users,
 
Due to process changes we have removed the undelivered roadmap items from this section and closed the related Project.
It is important to us that you continue to have visibility of our roadmap, so we will be sharing details regularly through other channels while we define the ideal way to share these details on GitHub.

Thank you for your understanding.
