### ISSUE TITLE
Payara 6 Enterprise

### ISSUE THREAD

**Issue by rdebusscher** [payara/Payara#5524]
Payara 6 Enterprise will be the stable, thoroughly tested, designed for mission critical environments, and long term supported (10 years lifecycle guarantee) version of Payara 6 Community.

**Comment by fturizo** [comment]
Dear users,
 
Due to process changes we have removed the undelivered roadmap items from this section and closed the related Project.
It is important to us that you continue to have visibility of our roadmap, so we will be sharing details regularly through other channels while we define the ideal way to share these details on GitHub.

Thank you for your understanding.
