### ISSUE TITLE
Jakarta EE 10 Core Profile Product

### ISSUE THREAD

**Issue by rdebusscher** [payara/Payara#5525]
Creation of a new product supporting the Core Profile of Jakarta EE.

**Comment by fturizo** [comment]
Dear users,
 
Due to process changes we have removed the undelivered roadmap items from this section and closed the related Project.
It is important to us that you continue to have visibility of our roadmap, so we will be sharing details regularly through other channels while we define the ideal way to share these details on GitHub.

Thank you for your understanding.
