### ISSUE TITLE
SSO not executing single logout properly /FISH-6047

### ISSUE THREAD

**Issue by jimmc929** [payara/Payara#5551]
We have developed a number of applications (WARs) and have deployed them on Payara 5-2021-10 with “Enable SSO” checked. These apps use Soteria (org.glassfish.soteria:jakarta.security.enterprise:1.0.1). We use the following annotation for our login bean:

`@FacesConfig(
	// Activates CDI build-in beans
	version = JSF_2_3 
)
@CustomFormAuthenticationMechanismDefinition(
    loginToContinue = @LoginToContinue(
            loginPage="/login.xhtml",
            errorPage="" // DRAFT API - must be set to empty for now
    )
)`

For this example, we will refer to two apps, “A” and “B.” For user convenience, both apps have “logout” buttons. 

We log in to app “A” and do some work. We then use a browser Favorites shortcut to go to app “B.” This works as expected- we are not asked to log in again. We do some work in app “B” and click that app’s logout button. This redirects us to the home page of app "B" and we see the login screen as expected. We then use a shortcut on our browser’s Favorites bar to go back to app “A.” Rather than asking for a new login, as it should (because the SSO session has been invalidated), app “A” allows us to continue working as if we had never logged out. 

The URLs for both apps have identical prefixes, i.e., https://domain/etc. In other words, they are using the same port number, machine domain, and protocol. 

This behavior is observed in a number of browsers (Chrome, Edge/Chromium, and Firefox). 

It seems that Payara is creating two different sessions for the two apps, and is not coordinating them on logout. Obviously this is a serious security issue. Any idea as to what may be causing it?

The logout logic is as follows:

`
// Try to retrieve our current session
            HttpSession session = request.getSession(false);
                        
            // Logout current request
            request.logout();
            
            // Invalidate session so user becomes anonymous.
            if (session == null) {
                LOGGER.log(Level.INFO, "Identity: No session to invalidate for user: {0}", userId);
            } else {
                session.invalidate();
                LOGGER.log(Level.INFO, "Session invalidated for user: {0}/{1}", new Object[] { userId, sessionId } );
            }
`

**Comment by sgflt** [comment]
This behaviour is already described in another issue  https://github.com/payara/Payara/issues/2881

**Comment by jimmc929** [comment]
Issue [2881](https://github.com/payara/Payara/issues/2881) describes a case of two apps where one login to an app is not part of SSO and an app pre-maturely times out. In our case, the user is properly logged in to both apps and access remains to one app even though the user has logged out of the SSO session. This seems like a much different (**and more serious**) situation.

Here is the quote from the 2881 issue:

> The problem is caused by the session created for app2 before login in app1. This session is not associated with SSO. Only login creates SSO cookie and following new sessions are associated with SSO id.
> 
> So in your case access to app2 does not trigger last access update in SSO, because for app2's session there is no SSO.

This is not the case in our scenario. Logging out of one app that is part of an SSO session should render other apps that are part of that SSO session inaccessible without logging in again.

**Comment by sgflt** [comment]
I think it is exactly the same scenario.

_1. We log into app “A” and do some work._ -> **this session is not associated to SSO**
_2. We then use a browser Favorites shortcut to go to app “B.” This works as expected- we are not asked to log in again. We do some work in app “B” and click that app’s logout button._  -> **B session is created and associated to SSO, therefore destroyed after logout. A is not destroyed because A is not associated to SSO**

**Comment by jimmc929** [comment]
I think I understand what you're saying, but I don't see why it should work this way? How does one get app "A" to participate in SSO? I assumed that including the CustomFormAuthenticationMechanismDefinition would accomplish that. Should we be doing something else? How does one properly use SSO if it's doing this? Do we need to call some other function after login to app "A" to back-register it with the (newer) SSO session?

**Comment by fturizo** [comment]
@jimmc929, apologies for the late reply. I've been testing the SSO behaviour in the latest release of Payara Server Community Edition and it works as advertised: If you login to application  A, you are automatically logged in to application B, and when logging out of application B, you are also logged out of application A and its session gets invalidated. For reference, here's what the documentation states how the SSO behaviour works:

> Single sign-on operates according to the following rules:
> * Single sign-on applies to web applications configured for **the same realm and virtual server**. The realm is defined by the realm-name element in the web.xml file. 
> * As long as users access only unprotected resources in any of the web applications on a virtual server, they are not challenged to authenticate themselves.
> * As soon as a user accesses a protected resource in any web application associated with a virtual server, the user is challenged to authenticate himself or herself, using the **login method defined for the web application** currently being accessed.
> * After authentication, the roles associated with this user are decisions across all associated web applications, without challenging the user to authenticate to each application individually used for access control
> * When the user logs out of one web application (for example, by invalidating the corresponding session), **the user's sessions in all web applications are invalidated**. Any subsequent attempt to access a protected resource in any application **requires the user to authenticate again**.
>
> The single sign-on feature utilizes HTTP cookies to transmit a token that associates each request with the saved user identity, so it can only be used in client environments that support cookies.

The SSO feature was originally designed to work out of the box with the traditional JAAS API, so I'm not sure how it is supposed to work when using the modern Jakarta EE Security API, since the cornerstone of the feature working is for all applications being configured **with a login method that points out to the same Security Realm**. Can you check if this is the case with your application? If so, can you please share a complete, self-contained reproducer that showcases the problem in detail?

**Comment by jimmc929** [comment]
Hi @fturizo thanks for your reply and for looking into this. It's a significant issue for us. We will create a public GitHub repo with a test project for reproducing this issue. In the meantime, I wanted to mention a few things that might help to trace the problem. 

SSO does seem to work properly for all applications except the first one that creates the SSO session. In other words, assume I have apps A, B, C, and D. I log in to A and do some work, go to B, do some work, go to C, do some work, and go to D to do some work. If I think log out of D, I will be logged out of applications B, C, and D, but NOT application A. Likewise, if I log in to A, do some work, go to B, C, and D and do some work, come back to A and log out of A, I will be logged out of application A but NOT any of applications B, C, or D. (By the way, this behavior is the same regardless of which app you start with - A, B, C, or D. The issue is always only with the first app- whichever it is.) Since all of the applications are compiled with exactly the same login library JAR, it would seem that realm is probably not the issue? Here is the declaration for our LoginBean (that is in the login library JAR):

`@FacesConfig(
	// Activates CDI build-in beans
	version = JSF_2_3 
)
@CustomFormAuthenticationMechanismDefinition(
    loginToContinue = @LoginToContinue(
            loginPage="/login.xhtml",
            errorPage="" // DRAFT API - must be set to empty for now
    )
)
@Named
@RequestScoped
public class LoginBean {`

This seems to suggest that SSO is basically working EXCEPT for the first login, which does not seem to be registered with the SSO session. (This is what prior commenters have observed also. See the prior entries referenced in this thread.)

We don't specify a login-config section in the web.xml because we understood that it was not necessary when using the annotations? But if it is necessary, what should we put in it? Just the realm name? Again, because of the behavior of apps B, C, and D in the scenarios described above, it doesn't seem like realm name would be a factor but we're happy to adjust the web.xml if you feel that is necessary. Thanks for your input!
Jim

**Comment by fturizo** [comment]
@jimmc929, as I explained in my previous post, the realm configuration is needed to make the SSO feature work, as it was designed using realms rather than the modern Jakarta EE security. As you are using the modern EE security API, you may try to configure an Identity Store mapped to a security realm (see [Realm Identity Stores](https://docs.payara.fish/community/docs/documentation/payara-server/public-api/realm-identitystores/README.html)) and check if the SSO feature works well. .

Nevertheless, the best way to check if this use case is fully supported is to prepare a self-contained reproducer that we can analyze.

**Comment by fturizo** [comment]
@jimmc929, have you been able to work on the self-contained reproducer that we requested in order to investigate this issue in more detail? Please share it as soon as you can.

**Comment by jimmc929** [comment]
Hi @fturizo, 
Yes, we have almost finished assembling the test repo. There are quite a few pieces to it. Should have it to you in a couple of days. Sorry for the delay- we are swamped with projects!
Jim

**Comment by jimmc929** [comment]
Question: What do we need to import to use the @RealmIdentityStoreDefinition annotation? It's not recognized by NetBeans. We are importing:

`    compile 'org.glassfish.soteria:jakarta.security.enterprise:1.0.1'
`
Is there a Payara-specific JAR that needs to be imported?

**Comment by fturizo** [comment]
Greetings @jimmc929, I have been able to reproduce the behaviour you described in the issue by testing the sample application that you shared. Indeed, the first application where the user logs in will not correctly log out when the user logs out from a different application. I tested this using a `@FileIdentityStoreDefinition`  mapping to the default `file` security realm instead of using a mock identity store and the same problem persists.  To this effect, I have raised the issue `FISH-6047` so that Platform Development may fix it in a future release.

However, as I stated previously, the SSO feature wasn't conceived with the Jakarta EE security API in mind (since it predates it by quite some time), so fixing this issue may take a considerable effort and thus has been deemed a low priority.
