### ISSUE TITLE
MicroProfile HashiCorp Secrets: getting connection refused

### ISSUE THREAD

**Issue by markusweisssiemens** [payara/Payara#5821]
Hi,

I'm using the following components:

- Payara 5.2022.2 community edition (Full)
- Docker Container with HashiCorp Vault 1.10.4 (running in dev-mode)

and followed the description from: https://docs.payara.fish/community/docs/5.2020.7/documentation/microprofile/config/cloud/hashicorp.html

I created a KV engine V2 with the following configuration / entries:

- Secrets engine path: secret
- Added a secret with path "test" and one secret data with key "content" and a value like "123"

Configured the MicroProfile HashiCorp page like (and added the token also in the password aliases):

- Enabled: true
- Dynamic: true
- API Version: 2
- Vault Address: http://localhost:8200
- Secrets engine path: secret
- Secrets path: test

If I query the values like:
`curl --header "X-Vault-Token: my-token-which-I-also-use-in-payara" http://localhost:8200/v1/secret/data/test`
I receive the correct answer which shows me my key/value pair "content":"123"

If I try in the asadmin to query it like:
`get-config-property --source cloud --sourcename hashicorp --propertyname content`
or
`get-config-property --source cloud --sourcename hashicorp --propertyname test`
I always get the answer "remote failure: content Not Found in source cloud" and in the logfile I see:
`Unable to read secret value
javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused: connect`

Afterwards I tried to reconfigure the MicroProfile HashiCorp page like (and added the token also in the password aliases):

- Enabled: true
- Dynamic: true
- API Version: 1
- Vault Address: http://localhost:8200
- Secrets engine path: sec1
- Secrets path: test

and enabled a KV engine V1 in Vault under sec1 and added a "test" secret with key "content" and value "123".

If I query the values like:
`curl --header "X-Vault-Token: my-token-which-I-also-use-in-payara" http://localhost:8200/v1/sec1/test`
I receive the correct answer which shows me my key/value pair "content":"123"

If I try in the asadmin to query it like:
`get-config-property --source cloud --sourcename hashicorp --propertyname content`
or
`get-config-property --source cloud --sourcename hashicorp --propertyname test`
I always get the answer "remote failure: content Not Found in source cloud" and in the logfile I see:
`Unable to read secret value
javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused: connect`

In the end I'm not able to connect to my Vault instance.

Any help would be appreciated.

**Comment by markusweisssiemens** [comment]
**Sorry** for bothering you. It seems now that we have installed Vault once more and configured with SSL certificate it started working!

**Comment by marif1989** [comment]
We have at least 70 Java applications and now trying to use the secrets that is saved from vault. The plan is to create no-root tokens in order to access the secrets from vault.
configured all required settings in payara5 server and able to connect to vault and able to get all the required secrets via non-root token.
The problem is non-root tokens are expiring too soon and payara5 is not renewing non-root token automatically and as soon as the token expire connection breaks and no secrets can be fetched from vault.

Reason to use non-root token is java applications must not see the secrets of each other.

Please suggest the possible ways to achieve requirement

Vault configuration is like:

Non-root token A must access only - /DEV/APP-A
Non-root token B must access only - /DEV/APP-B
