### ISSUE TITLE
Bean validation is jax-rs

### ISSUE THREAD

**Issue by rangalo** [payara/Payara#611]
When using a stateless ejb as jax-rs controller, the bean validation works that means I get HTTP 400 status with HTML error message, but there is no exception thrown. The exception mapper doesn't get called.   

Here is the SO question for that. 

http://stackoverflow.com/questions/34832330/jax-rs-bean-validation-exception-mapper-in-payara-4-1?stw=2

**Comment by abhirockzz** [comment]
Here is an educated guess:

For the ExceptionMapper to be triggered, an exception should be thrown from the JAX-RS resource method. In this case the bean validation triggers during the injection of 'User' into the method (AOP/interceptor style). The validation fails and the method is never called. I think it is just a coincidence that you have configured your mapper to return a Response.Status.BAD_REQUEST (which internally maps to HTTP 400).

You can try this with another combination of a mapper and an exception and throwing it explicitly from the JAX-RS resource method (just to make sure it gets invoked)

**Comment by rangalo** [comment]
Hi, 

I think, you are right and there is no exception thrown at all. My other exception mapper are being called but those exceptions occur later in the method. 

But then there should be a way to get the validation errors and customize the error response as shown here 
http://samaxes.com/2014/04/jaxrs-beanvalidation-javaee7-wildfly/

I will try something like this in wildfly, but if this works in wildfly, then payara behaves differently than specs.

**Comment by abhirockzz** [comment]
Ok. At least something is clear [ I hope :-) ]

As far as trying it out in other containers (e.g. Wildfly etc.) is concerned - I am not sure if that's an accurate approach. The reason being that other containers might provide some 'addon' functionality/enhancement - this does not mean that Payara is not following the spec. All I am saying is that the best place to confirm this would be the JAX-RS and Bean Validation spec docs. 

I will do the same once I have some time

**Comment by abhirockzz** [comment]
I am not sure if you have already explored the required spec documents, but here are my inputs

1. The HTTP 400 is as a result of the default JAX-RS exception mappers (this is mandated by the specification)
2. One *can* override the default behaviour: I tried this with success
3. Looks like Payara is behaving as per spec. You would need to map against the ConstraintViolationException rather than ValidationException (as you have mentioned in the SO post)

In case you're interested

1. Here is a [brief blog entry](https://abhirockzz.wordpress.com/2016/01/22/bean-validation-in-jax-rs/) I posted
2. A small [maven based Java EE 7 sample](https://github.com/abhirockzz/JAX-RS-and-Bean-Validation) I put together to validate this (using 4.1.1.154 build 270)

**Comment by smillidge** [comment]
@abhirockzz thans for helping out. @rangalo does this clear it up for you?

**Comment by rangalo** [comment]
Hi @abhirockzz @smillidge  ,

it works perfectly. The only problem was that I was using ValidationException instead of ConstraintViolation Exception.

**Comment by smillidge** [comment]
Thanks guys for fixing this.
