### ISSUE TITLE
Bug Report: Vuln Scan Results

### ISSUE THREAD

**Issue by EggShellCap** [payara/Payara#6136]
### Brief Summary

Vulnerability scan ran against community edition found the following CVEs:

CVE-2016-1906
CVE-2021-23463
CVE-2021-42392
CVE-2022-23221
CVE-2022-42003
CVE-2022-42004
CVE-2016-1905
CVE-2016-7075
CVE-2022-37422
CVE-2022-45129
CVE-2022-45868

### Expected Outcome

- Recommendations for running version 1.x
- Is it possible to replace H2 database with Apache Derby

### Current Outcome

Not able to upgrade due to base JDK version 1.8.

### Reproducer

Reproduceable by running Grype vulnerability scanner.

### Operating System

Windows & Linux

### JDK Version

JDK 1.8

### Payara Distribution

Payara Embedded Web

**Comment by shub8968** [comment]
Hi @EggShellCap,

1. CVE-2016-1906 is specific to Openshift.
2. CVE-2021-23463 H2 is upgraded in Payara6 to 2.1.212. 
3. CVE--2021-42392 H2 is upgraded in Payara6 to 2.1.212.
4. CVE-2022-23221 H2 is upgraded in Payara6 to 2.1.212.
5. CVE-2022-42003 is tracked as FISH-6629 in our Backlog. It is fixed in Jackson 2.14.0 (not properly released yet, only RCs available.)
6.  CVE-2022-42004 same as point 5.
7. CVE-2016-1905 is specific to Kubernetes.
8. CVE-2016-7075 is specific to Openshift.
9. CVE-2022-37422 is fixed in Payara 2022.3
10. CVE-2022-45129 I will be back soon on it.
11. CVE-2022-45868 is specifc to H2. No fix has been implemented for it. Moreover, we don’t recommend using H2 on production systems.
