### ISSUE TITLE
Bug Report: Payara Micro 6.2022.2 --nocluster not working/FISH-6982

### ISSUE THREAD

**Issue by brunogptavares** [payara/Payara#6154]
### Brief Summary

Apparently the --nocluster option doesn't seem to be working in Payara Micro 6.2022.2 and 5.2022.5, it worked fine in version 5.2022.3.

### Expected Outcome

Output of Payara Micro 5.2022.3 as an example: 
```
{
    "Instance Configuration": {
        "Host": "BT-PC.mshome.net",
        "Http Port(s)": "8080",
        "Https Port(s)": "",
        "Instance Name": "payara-micro",
        "Instance Group": "no-cluster",
        "Deployed": [
        ]
    }
}
5.2022.3 #badassmicrofish (build 308) ready in 2á273 (ms)
```

### Current Outcome

Payara micro 5.2022.5:
```
...
{
    "Instance Configuration": {
        "Host": "BT-PC.confidentia.pt",
        "Http Port(s)": "8080",
        "Https Port(s)": "",
        "Instance Name": "Modern-Catfish",
        "Instance Group": "MicroShoal",
        "Hazelcast Member UUID": "d1d06b1b-006d-45ea-817b-1f79a55b3851",
        "Deployed": [
        ]
    }
}
...
5.2022.5 #badassmicrofish (build 492) ready in 7á952 (ms)
```

Payara Micro 6.2022.2:
```
    "Instance Configuration": {
        "Host": "BT-PC.confidentia.pt",
        "Http Port(s)": "8080",
        "Https Port(s)": "",
        "Instance Name": "Ugly-Carp",
        "Instance Group": "MicroShoal",
        "Hazelcast Member UUID": "10a3b8de-8369-44cd-832b-e6995d9e39bd",
        "Deployed": [
        ]
    }
}
...
6.2022.2 #badassmicrofish (build 881) ready in 22á224 (ms)

```
It took 22 seconds to boot!

### Reproducer

Just run:
`java -jar payara-micro-6.2022.2.jar --nocluster`

### Operating System

Windows 11 Pro

### JDK Version

Temurim JDK 17.0.4.1

### Payara Distribution

Payara Micro

**Comment by JamesHillyard** [comment]
Hi @brunogptavares,

There was a change in Payara Community 5.2022.4 and Payara Community 6.2022.1 which changed the behaviour of the `--noCluster` option in Payara Micro.

Previously the `--noCluster` option was used to disable both Hazelcast and clustering on a Payara Micro instance. In Payara Micro Community 5.2022.4/6.2022.1 and later the `--noCluster` option will still leave Hazelcast enabled, allowing for the use of Hazelcast dependant features such as JCache, while still disabling clustering. 

To disable both clustering and Hazelcast on Payara Micro you should now use the `--noHazelcast` option instead of `--noCluster`.

I suspect this is the difference you are experiencing, could you please try using `--noHazelcast` as a replacement to `--noCluster` and confirm you get the expected behaviour?

Thanks,
James

**Comment by brunogptavares** [comment]
Hi @JamesHillyard 

That's correct, it works as expected with `--noHazelcast`.

Thanks
Bruno
