### ISSUE TITLE
Bug Report:  All instances in this deployment group will have the same set of resources (NOT TRUE)

### ISSUE THREAD

**Issue by roberto-cisternino** [payara/Payara#6165]
### Brief Summary

In the latest Payara 5 Deployment Groups are not sharing resources with associated instances.

### Expected Outcome

All instances in a deployment group must have the same set of resources.

### Current Outcome

No resource (jndi, jdbc, mail, ...) is shared with its instances

### Reproducer

Create a JDBC resource
Create a Deployment Group
Create an Instance
Associate the above JDBC resource to the Deployment group
Stop/Start domain
Start the Deployment Group

The instance and a basic web app cannot access the JDBC resourse.

WORKAROUND
It is necessary to associate the JDBC resource to the instance as well in order to work.

But DeploymentGroup this way are pretty unuseful !

### Operating System

Windows 10

### JDK Version

Oracle JDK 8.212

### Payara Distribution

Payara Server Full Profile

**Comment by felixif** [comment]
Hello @roberto-cisternino,

I have followed your steps in order to reproduce the behaviour described by you. Indeed, without associating the JDBC Resource that I used to access my MySQL database, the application would throw a 500 error when trying to access one endpoint associated with a database call. But you can add multiple instances to the target of the JDBC Resource, so you can just add all the instances that you need to have access.

**Comment by felixif** [comment]
Hello @roberto-cisternino,
As we haven't received any updates on this issue, we'll proceed to close it.
