### ISSUE TITLE
Failure in postbootcommandfile ignored

### ISSUE THREAD

**Issue by janArb** [payara/Payara#6382]
### Brief Summary

I made an escaping error in the postbootcommandfile and noticed, that the payara continued to boot. A warning message was logged.

### Expected Outcome

By default all errors should prevent the payara to boot. If one prefers to ignore errors this could be activated separately.

### Current Outcome

Error is ignored and Payara boots.

`2023-08-28 14:52:21 [#|2023-08-28T12:52:21.767+0000|WARNING|Payara 6.2023.8|fish.payara.boot.runtime.BootCommand|_ThreadID=29;_ThreadName=RunLevelControllerThread-1693227138400;_TimeMillis=1693227141767;_LevelValue=900;|
2023-08-28 14:52:21   Boot Command create-jvm-options failed PlainTextActionReporterFAILUREDescription: create-jvm-options AdminCommandJVM option +UseG1GC is invalid because it does not start with a '-'
2023-08-28 14:52:21     null
2023-08-28 14:52:21  |#]`

### Reproducer

echo "create-jvm-options -- -XX:+UseG1GC" >> postbootcommandfile

Correct is to escape the colon with backslash...

### Operating System

Ubuntu 22.04

### JDK Version

zulu11

### Payara Distribution

Payara Docker Image

**Comment by shub8968** [comment]
Hi @janArb,

As [documented](https://docs.payara.fish/community/docs/Technical%20Documentation/Payara%20Micro%20Documentation/Payara%20Micro%20Configuration%20and%20Management/Micro%20Management/Asadmin%20Commands/Pre%20and%20Post%20Boot%20Commands.html#boot-scripts-with-persistent-rootdir), by design,  the said behavior is default of Boot Scripts. You can raise an enhancement request pertaining to it.
