### ISSUE TITLE
Bug Report: start-domain no longer wait for application to be deployed.

### ISSUE THREAD

**Issue by Tenariel** [payara/Payara#6453]
### Brief Summary

With the migration of payara 5 to payara 6, I observe a change in behavior of the command <asadmin start-domain >.
In payara5, when the server starts with an already deployed application, the start-domain wait for all applications to be started. The status of the command depends on the capability of the server to start all applications and if the applications could not be started, the start-domain clearly displays an error. 
Now in payara6, when the server starts, the asadmin command hand over control before applications are started. We have no way (to my knowledge) to get programmatically the information that applications are started or is in error state after a server restart. 

### Expected Outcome

Same behavior between payara 5 and payara 6

### Current Outcome

The payara <asadmin start-domain> command give back control before applications finish their starts. The only way we found to know if the applications is started or failed to start is to check the logs. 

I made my test with a payara 6.2023.9 and a payara 5.2022.5

### Reproducer

I created 2 web application that show a web page helloworld and have a Timer.Sleep(50000) in a @postconstruct (I can provide it if needed). The first one used javax package for payara5 and the other one used Jakarta package for payara6.
When I deploy the application on each server, the deployment take ~ 50s. 
If I stop and start each server, payara5 take ~1 minute before hand over control. Payara 6 take ~ 10s to start and we can see in the logs the application is not finished to be started.

### Operating System

alpine

### JDK Version

JDK 17.0.8.7.1 for payara 6 and JDK 11.0.17 for payara 5

### Payara Distribution

Payara Server Full Profile

**Comment by Elifzeynepedman** [comment]
Hi @Tenariel,

Would you be able to provide the sample reproducers which you have used?

Best Regards,
Elif

**Comment by Tenariel** [comment]
Hi Elifzeynepedman,

Thank you for your answer. 

These are default maven web projects created by netbeans. I just add a method in the Application class to delay the deployment :

[helloWorldJakartaWeb.zip](https://github.com/payara/Payara/files/12999115/helloWorldJakartaWeb.zip)
[hellowWorldJavaxWeb.zip](https://github.com/payara/Payara/files/12999118/hellowWorldJavaxWeb.zip)

**Comment by Tenariel** [comment]
Hi,

For your information, This issues is still reproducible with the latest version of payara (6.2023.11).

**Comment by felixif** [comment]
Hello @Tenariel,

You are right, the issue is still reproducible. In my tests, the difference in deployment behaviour seems to come from the JDK version used for testing. In my case, Payara 6.2023.11 with JDK 11 the deployment time is 55.85s (identical to 5.2022.5 on JDK 11) and with JDK 17 the time is 21s. 

The problem is that I am unable to see a difference in the logs of the two applications besides the different time it took to deploy. Are you able to share the logs of your run of the reproducer? Or could you tell me if you changed the default logging values, and what value should I change to see the issue you are encountering?

Best regards,
Felix Ifrim

**Comment by Tenariel** [comment]
To be honest, I opened this ticket because we observed a difference in payara's behavior during our migration from payara5 to payara6. 

The example i sent was to simplify the issue to know if the issue come from my application or from Payara.

If you want more trace, could you tell me which direction i can search to help you ? 

Regards,

Tenariel

**Comment by Tenariel** [comment]
@fabide Unfortunately not. We've modified our startup script to pool a REST endpoint to check whether the application is started or not. 
For information, we test with JDK 21 and the issue is still here (with payara 6.2023.9).

**Comment by Hapi** [comment]
I totally understand @Tenariel’s problem. When a management tool like Ansible or Puppet is used there is no easy way to know when the domain has started anymore. The behavior of Payara has changed so that `asadmin start-domain my-domain` now returns after a few seconds after the command execution but in reality the startup process is still in progress. This is easily noticed (from server.log) when there are around 100 web applications deployed on a domain.

Previously (Payara 5) the command used to wait until the domain has really started but now (Payara 6) it seems return right after the startup process has initiated.

The problem for management tools (or scripting) is that we used to rely on a fact that the startup has finished when `asadmin start-domain my-domain` returns but now we cannot rely on that anymore but instead try to do some tricks to figure out if the domain has started or not.

I personally hope that `asadmin start-domain my-domain` would work as it used to work in Payara 5, perhaps with a command line option like `--wait-until-finished` or something.
