### ISSUE TITLE
Bug Report: Payara API packages not released to Maven Central or Payara Nexus since 6.2023.9

### ISSUE THREAD

**Issue by poikilotherm** [payara/Payara#6547]
### Brief Summary

`fish.payara.api:payara-api` packages have not been released since the 6.2023.10+ releases.

### Expected Outcome

Using Payara 6.2023.10+ BOM I expected the corresponding version of the API package.

### Current Outcome

```
Could not resolve dependencies for project edu.harvard.iq:dataverse:docker-build:6.1: The following artifacts could not be resolved: fish.payara.api:payara-api:jar:6.2024.1 (absent): Could not find artifact fish.payara.api:payara-api:jar:6.2024.1 in payara-nexus-artifacts (https://nexus.payara.fish/repository/payara-artifacts)
```

Nothing to be found for recent releases at https://mvnrepository.com/artifact/fish.payara.api/payara-api or https://nexus.payara.fish/#browse/browse:payara-artifacts:fish%2Fpayara%2Fapi%2Fpayara-api

### Reproducer

Create a Maven POM, add
```
        <dependency>
            <groupId>fish.payara.api</groupId>
            <artifactId>payara-api</artifactId>
            <scope>provided</scope>
            <version>6.2024.1</version>
        </dependency>
```
and watch it fail building.

### Operating System

Linux 6.6.13-200.fc39.x86_64

### JDK Version

Temurin 17.0.9

### Payara Distribution

Payara Server Full Profile

**Comment by pzygielo** [comment]
> Using Payara 6.2023.10+ BOM I expected the corresponding version of the API package.

If using BOM - why would you specify `payara-api` separately instead of importing its version from BOM?

https://repo.maven.apache.org/maven2/fish/payara/api/payara-bom/6.2024.1/payara-bom-6.2024.1.pom manages this
![image](https://github.com/payara/Payara/assets/11896137/bd752213-d613-4f9c-b6d1-7a06a524ee3c)

It's in Payara's nexus:
![image](https://github.com/payara/Payara/assets/11896137/66e96765-c99d-4d0b-9956-518581efb057)

Side note: it's missing from central, which I find not cool...

**Comment by poikilotherm** [comment]
@pzygielo since 6.2023.8+ the `payara-api` dependency has been removed from the BOM (AFAIK without announcement), ([see also comment in our Dataverse project](https://github.com/IQSS/dataverse/blob/97508e61b9d1ba99c63412248a27f7bbbf99b575/pom.xml#L200-L202))
