### ISSUE TITLE
Bug Report: Docker container doesn't start anymore in case of JVM option with spaces in value 

### ISSUE THREAD

**Issue by jaylemur** [payara/Payara#6638]
### Brief Summary

Container doesn't start anymore if a JVM options is configured in the domain with one or more space(s) in the value.

### Expected Outcome

Container starts successfully.

### Current Outcome

Domain doesn't start with an error message saying that it cannot find the main class

### Reproducer

* Start a container with the last image of Payara full server
* Using the console, add a new JVM options with a value that contains spaces for example: 
  -Djames.smtp.smtpGreeting=“ESMTP Server by xxx”
* The container doesn’t restart anymore and you can see the error message : Error: Could not find or load main class Server

### Operating System

Window 10 pro + Docker Desktop 

### JDK Version

Version from Payara image, tag latest

### Payara Distribution

Payara Docker Image

**Comment by artur-mal** [comment]
The issue you’re experiencing is not specifically a problem with Payara or Docker. It’s more about how JVM options are passed and interpreted.
You can try enclosing the entire system property in quotes:

`-D"james.smtp.smtpGreeting=ESMTP Server by xxx"`

Make sure you don't use non-standard quotation marks (“” instead of "). When setting JVM options, it’s important to use standard ASCII double quotes (").

**Comment by jaylemur** [comment]
Thanks for your hint, but I think that the problem is more related to the way the script "startInForeground.sh" starts the domain.
First it takes the output of the command start-domain with the "--dry-run" option.
Makes some string manipulation using "sed" and use the result as the final command to start the domain.
Unfortunately, the ouput of the command with *--dry-run" already removes any quotes
