### ISSUE TITLE
Bug Report: Payara Micro v6.2024.6 Reporting as v6.2024.5

### ISSUE THREAD

**Issue by mzaum** [payara/Payara#6766]
### Brief Summary

When launching Payara Micro v6.2024.6, it is logging that it is version v6.2024.5.

` [2024-06-19T10:56:23.839-0400] [] [INFO] [] [PayaraMicro] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1718808983839] [levelValue: 800] Payara Micro 6.2024.5 #badassmicrofish (build 18) ready in 13,817 (ms)`

### Expected Outcome

Logs should show v6.024.6.

### Current Outcome

Logs show v6.2024.5.

### Reproducer

Simply launch Payara Micro.

### Operating System

Ubuntu 22.04

### JDK Version

OpenJDK Runtime Environment (build 11.0.23+9-post-Ubuntu-1ubuntu122.04.1)

### Payara Distribution

Payara Micro

**Comment by kalinchan** [comment]
Works on my machine.

`[2024-06-19T16:48:16.797+0100] [] [INFO] [NCLS-CORE-00017] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1718812096797] [levelValue: 800] Payara Micro 6.2024.6 #badassmicrofish (19) startup time : Embedded (921ms), startup services(4,725ms), total(5,646ms)`

**Comment by mzaum** [comment]
So it turns out I was pointing it at an existing `--rootdir`.  Deleting that root dir and creating a new one fixed it.  Is that expected behavior?

**Comment by felixif** [comment]
Hello @mzaum, 

I tried your case just now. I first started a Payara Micro 6.2024.5 with a rootdir created under `{path_to_jar}\tmp\pm-domain`. This created the domain folder, that has under `\config\branding` a `glassfish-version.properties` file. This file is the one responsible for reporting the number. I then ran Payara Micro 6.2024.6 pointing at the same `pm-domain` folder, and I noticed that the `glassfish-version.properties` does not change. 

I assumed that this is because the file is present and Payara assumes it is ok, so I decided to simply delete it and re-run Payara Micro 6.2024.6 to see what happens. The file gets re-created, so I believe this is intended. Simply delete the file when you switch the versions and it should be fine. But it might be a good idea to also document this behaviour.

Best regards,
Felix
