### ISSUE TITLE
default-logging.properties appears to be required and overlap with logging.properties

### ISSUE THREAD

**Issue by FireballDWF** [payara/Payara#713]
Why does /opt/payara41/glassfish/domains/payaradomain/config contain both default-logging.properties and logging.properties?  

When I delete the default- one, an HTTP status code=500 is returned for https://10.0.4.127:4848/common/configuration/loggerGeneral.jsf?configName=server-config.

My goal is to get to a single version of these two files, so I only have to maintain it once for integration with logstash via the gelf format.  You can see what I'm doing at https://github.com/FireballDWF/docker-alpine-payara-logstash

**Comment by OndrejM** [comment]
The file `default-logging.properties` is only used to provide a back-up of properties, in case it is necessary to revert configuration to default values (see *Load defaults* button in the admin console). The default file is not really necessary, the administration console page just expects that it exists, which could be fixed. You may even clear the contents of the default file, provided that the file itself remains, and admin console works without a problem and stops throwing errors. In such case, pressing "Load defaults" button will do nothing.

The actual configuration is read from and stored to `logging.properties` file, and is single source of truth. The default file is not considered when reading logging configuration.

It is enough to maintain `logging.properties` file and forget `default-logging.properties`, the default file just needs to remain there so that admin console does not throw errors. If you want to explicitly clean the default values, you may leave `default-logging.properties` completely empty.
