### ISSUE TITLE
Does Payara Micro has support for the JMS

### ISSUE THREAD

**Issue by rajsinhak** [payara/Payara#869]
I find the Payara Micro very helpful for my application architecture, Currently was able to execute parallel job under JBatch. As my requirement is to have multiple batch executor to run synchronous, So i need to deploy as multiple micro services, so to interact with micro services i planned to have JMS and XA for global transaction. Do wanted to check if Payara Micro Supports JMS and XA .

**Comment by fturizo** [comment]
Hi @rajsinhak. Considering that Payara Micro is based off the Payara Embedded Web release, which is based on Glassfish Web profile, it doesn't support JMS and the complete EJB API by default (no distributed transactions - XA in this case). 

Do you have an specific use case for these microservices to use JMS and XA to coordinate this global transactions?

**Comment by rajsinhak** [comment]
Hi Turizo,
  Thanks for your response, Yes we have a specific use case. there's what we tries to achieve, 
  upfront we will have a batch manager/requester, which will be able to invoke N Batch Group which can be Sync and Async . as since we though of building each batch executor as micro service in each batch group which can again run some parallel jobs. now some the batch executor may be on different AP/DB server. so need JMS as communicator and to maintain transaction between each micro service(whether on Same AP server or different AP Server) we need a JTA XA as global transaction handler. The Idea to choose batch executor as each Micro Service as we wanted a independent service which can be changed later or will be able to add a new batch executor without changing the whole architecture
Hope you got the use case !!

**Comment by fturizo** [comment]
Yeah I understand the use case. Since there's a dependency to **JMS** for async communication and for **JTA** with **XA** to coordinate the transactions I think the full version of Payara is needed in this case. Have you considered using **Docker** for this use case? You can create a new image based on the [payara full version](https://hub.docker.com/r/payara/server-full/) and use it to deploy each microservice. I know that this image is not as light as the micro one, but with this you can mount your microservice infrastructure with JMS and JTA support. Using Docker Compose and Swarm can ease this task as well.

Let me know if this advice is of any help.

**Comment by mikecroft** [comment]
Hi @rajsinhak - does @fturizo's response answer your question? JMS is not supported by Payara Micro, but a JMS client can be written in Java SE if needed. Otherwise, our solution would be to use full Payara Server.

**Comment by mikecroft** [comment]
Assuming this is resolved now. Please reopen if not.
