### ISSUE TITLE
Allow multiple lines scripts when using the property "javax.persistence.schema-generacion.create-script-source" in persistence.xml

### ISSUE THREAD

**Issue by rulyone** [payara/Payara#874]
Hello.

Assuming this persistence.xml configuration:

``` xml
<property name="javax.persistence.schema-generation.database.action" value="create"/>
<property name="javax.persistence.database-product-name" value="PostgreSQL" />
<property name="javax.persistence.database-major-version" value="9" />
<property name="javax.persistence.database-minor-version" value="1" />
<property name="javax.persistence.schema-generation.create-script-source" value="META-INF/my_script.sql" />
<property name="javax.persistence.schema-generation.create-source" value="script" />
```

This script (my_script.sql) doesn't work when deploying an application:

``` sql
CREATE TABLE
foo;
```

But this script does work:

``` sql
CREATE TABLE foo;
```

I know it's not a stopper issue, but I would like to keep my code ordered and 1 liner scripts sometimes are harder to read, obviously this is not the case.

[This question](http://stackoverflow.com/questions/21729097/jpa-eclipselink-create-script-source-with-one-sql-statement-taking-multiple) in stackoverflow talks about the problem:

**Comment by vkalayda** [comment]
Hello everyone, we faced too with this problem. I think this is EclipseLink problem, am I right?

**Comment by OndrejM** [comment]
I understand that it is a serious pain, but it would make more sense to raise an issue on EclipseLink bug tracker. Even if it is fixed in Payara Server, it should be backported as a fix to EclipseLink, as it does not fix standalone EclipseLink.
Would you raise the issue also for EclipseLink and post a link here?

**Comment by OndrejM** [comment]
It seems that for some reason, Eclipselink parses the SQL file and executes SQL commands line after line. I don't see a reason why, possibly to avoid loading a huge SQL script into the memory.

A possible workaround would be to use a custom java.io.Reader and supply its class instead of the path to the SQL script. Eclipselink will then instantiate your reader instead of reading a DDL script. In your reader, you can read the SQL file and format (e.g. remove all new lines, and then replace each semicolon with a new line).

As there's no easy way to fix this behavior in Payara server without patching Eclipselink, I recommend to raise a bug for Eclipselink and close this issue for Payara. In other words, we don't have any plans to fix this in Payara server unless it is fixed in the Eclipselink project itself.

**Comment by lprimak** [comment]
If you paste the EL JIRA, we can vote for it

**Comment by vkalayda** [comment]
@OndrejM You are absolutely right.

**Comment by mikecroft** [comment]
Closing since this needs to be dealt with via EclipseLink. As above, please feel free to comment with any bug raised against EL.
