### ISSUE TITLE
Provide default group to role mapping

### ISSUE THREAD

**Issue by ggam** [payara/Payara#906]
Most of the time a 1:1 group to role with same name mapping is done and so the glassfish-web.xml could be avoided. 

This is already done by WildFly and is proposed for JSR 375 (Security API).

An option should be added to revert to the original behaviour where no automatic mapping is done.

**Comment by smillidge** [comment]
There is a configuration option to switch this on although by default it is not enabled. It is enabled in the admin console in the server-config -> security

**Comment by ggam** [comment]
Nice to see that! What about enabling in by defaut on payaradomain? Everybody that uses roles right now has to be providing a glassfish-web.xml file, that would override default mappings, so I don't think anybody could be affected from the incompatibility.

**Comment by mikecroft** [comment]
There is a current internal issue open to review and add some extra functionality to the payaradomain (e.g. extra stuff we've added in recent releases). I've added this request to that issue (PAYARA-846)

**Comment by ggam** [comment]
Thank you!

**Comment by arjantijms** [comment]
>This is already done by WildFly and is proposed for JSR 375 (Security API).

Indeed, in JSR 375 we hope to be able to introduce a portable switch to enable 1:1/default group to role mapping.

It's perhaps interesting that both WebLogic and Liberty switched from mandated group to role mapping, to default group to role mapping. Liberty under special conditions (when there's no so-called UserRegistry present). TomEE and JBoss never had mandated group to role mapping. Geronimo had this too, but is discontinued. This would make Payara one of the last servers to mandate this.

If changing the default is not (yet) an option, it would also help greatly to have the option to set default group to role mapping in glassfish-web.xml, instead of only via server-config -> security.

**Comment by lprimak** [comment]
I'll take a look at this... thanks!

**Comment by lprimak** [comment]
The following parsers need to be modified:
- glassfish-web.xml
- glassfish-application.xml
- glassfish-ejb-jar.xml

**Comment by lprimak** [comment]
You can now add the following to:

- glassfish-web.xml
- glassfish-ejb-jar.xml
- glassfish-application.xml

```<property name="default-role-mapping" value="true"/>```

to enable or disable default group mapping.
Keep in mind that in EAR deployments, glassfish-application.xml is the only one that takes effect, and not glassfish-ejb-jar.xml or glassfish-web.xml

**Comment by arjantijms** [comment]
>``<property name="default-role-mapping" value="true"/>``

Really cool, and a great step forwards for portable authentication!

**Comment by ggam** [comment]
Fantastic, thanks!
