### ISSUE TITLE
Environment to run GF and Payara in paralell

### ISSUE THREAD

**Issue by edilmar** [payara/Payara#962]
Hi,

I have servers running GF 3.1.2.2 in production.
I had planned the migration to Payara 4.1.1.
First of all, I created a CLI script to make all the configurations and tested locally in my development environment. All worked fine.
Now, I would like to install Payara in paralell at the same production server of GF, to run the CLI script and verify some problems could exist. Then, I need to change all ports for Payara use alternatives.
1) Are these the ports used?
Informações:   Grizzly Framework 2.3.24 started in: 42ms - bound to [/0.0.0.0:8080]
Informações:   Grizzly Framework 2.3.24 started in: 4ms - bound to [/0.0.0.0:8181]
Informações:   Grizzly Framework 2.3.24 started in: 8ms - bound to [/0.0.0.0:4848]
Informações:   Grizzly Framework 2.3.24 started in: 7ms - bound to [/0.0.0.0:3700]
2) What is the config file to change these ports before to start up the Payara server?

**Comment by lprimak** [comment]
@edilmar What I would suggest is to use ```asadmin create-domain``` to create a new domain from scratch.  It has ```--portbase``` parameter that specifies the base of all ports that are going to be used by Payara.
Barring that, you could go through the admin console to change these ports manually.

**Comment by mikecroft** [comment]
+1 for `--portbase`. I think that's what we use in our automated testing, because that needs to run multiple domains. As for the ports, there are a few more than those:

the DAS, by default, has the following ports:

|Property|Default Ports|
|---|---|
|HTTP|4848,8080,8181|
|IIOP|3820,3920,3700|
|JMS|7676|
|JMX|8686|

Any other instance will have these defaults (the defaults are automatically incremented by 1 if they are in use by an existing instance known to the DAS)

|Property|Default|
|-----------|----|
|ASADMIN_LISTENER_PORT      | 24848|
|HTTP_LISTENER_PORT         | 28080|
|HTTP_SSL_LISTENER_PORT     | 28181|
|IIOP_LISTENER_PORT         | 23700|
|IIOP_SSL_LISTENER_PORT     | 23820|
|IIOP_SSL_MUTUALAUTH_PORT   | 23920|
|JAVA_DEBUGGER_PORT         | 29009|
|JMS_PROVIDER_PORT          | 27676|
|JMX_SYSTEM_CONNECTOR_PORT  | 28686|
|OSGI_SHELL_TELNET_PORT     | 26666|

**Comment by edilmar** [comment]
I got to test the configuration in Payara domain2.
Thanks a lot.
