### ISSUE TITLE
Inline XSD into generated WSDL /CUSTCOM-59

### ISSUE THREAD

**Issue by Hoobie** [payara/Payara#994]
According to the untouched JIRA issue from Glassfish: https://java.net/jira/browse/GLASSFISH-20168
I would suggest adding the -inlineSchema option to the web console. Thank you.

**Comment by mikecroft** [comment]
I've created internal issue `PAYARA-966` for this enhancement

**Comment by rdebusscher** [comment]
Now internal issue `CUSTCOM-59`

**Comment by AlanRoth** [comment]
Hi, due to how long ago this issue was raised we have decided to close the issue immediately, and not consider the implementation of the fix/improvement that was requested. Please understand that this decision was taken into consideration with the resources that we have available at the moment. In case of having reported a bug, if the issue is still pressing to you, feel free to verify if it’s applicable in the current release of Payara Community edition, and proceed to raise a new issue with details of the test reproducer. Many thanks for your understanding.
