### ISSUE TITLE
 http or https listener port is occupied while server is not running

### ISSUE THREAD

**Issue by karenworld** [payara/Payara#999]
I wish to know how to make Payara server run, cos I keep getting this errro.

Have reinstalled Payara - not working.

Changed the domain1 port to 9090 - not working

Changed the System port to run on PID 5 cos it is this port that occupies the port 8080 - not working.

I need to get Payara server to up and running cos I need to hand in my project by Monday.

Please help. Tks.

**Comment by mikecroft** [comment]
If the default ports are taken and you're on a deadline, the quickest way to change all the ports to something else is to create a new domain with the `--portbase` option. If you run this command:

```
asadmin create-domain --portbase 5000 mydomain
asadmin start-domain myDomain
```

You will find that all your ports will begin with that number. This is because Payara will assign ports like:

* Administration port: portbase + 48
* HTTP listener port: portbase + 80
* HTTPS listener port: portbase + 81

So your admin console will be on `https://localhost:5048` and your application will be on, e.g. `http://localhost:5080/myApp`

**Comment by karenworld** [comment]
OK. Tks for taking time to reply.  I managed to changed the port to 9090 on Sunday which eats up most of my project time...:(
I did the changing via the config file in both the domain and domain1.
Will try out your method when I am free.
Once again, thank you so much for your reply.

**Comment by mikecroft** [comment]
No problem. Do be aware that if you're changing the `domain.xml`, there are two configurations there - `default-config` and `server-config`.

* The `default-config` is there as a template only and is never used (unless you explicitly try to use it, which is not recommended).
* The `server-config` is the configuration which is used for the `DAS` - the out-of-the-box server that starts with the domain and takes care of admin.

If you made the change in the `default-config`, then the change wouldn't have had any effect. It would only have taken effect in the `server-config`.

I'll close this issue now, feel free to comment again if you need any other help.
